// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mineserver/v1/file.proto

package mineserverv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/athNdev/mineserver/pkg/proto/mineserver/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "mineserver.v1.FileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FileServiceListFilesProcedure is the fully-qualified name of the FileService's ListFiles RPC.
	FileServiceListFilesProcedure = "/mineserver.v1.FileService/ListFiles"
	// FileServiceGetFileProcedure is the fully-qualified name of the FileService's GetFile RPC.
	FileServiceGetFileProcedure = "/mineserver.v1.FileService/GetFile"
	// FileServiceSaveUploadedFileProcedure is the fully-qualified name of the FileService's
	// SaveUploadedFile RPC.
	FileServiceSaveUploadedFileProcedure = "/mineserver.v1.FileService/SaveUploadedFile"
	// FileServiceUpdateFileProcedure is the fully-qualified name of the FileService's UpdateFile RPC.
	FileServiceUpdateFileProcedure = "/mineserver.v1.FileService/UpdateFile"
	// FileServiceDeleteFileProcedure is the fully-qualified name of the FileService's DeleteFile RPC.
	FileServiceDeleteFileProcedure = "/mineserver.v1.FileService/DeleteFile"
	// FileServiceRenameFileProcedure is the fully-qualified name of the FileService's RenameFile RPC.
	FileServiceRenameFileProcedure = "/mineserver.v1.FileService/RenameFile"
	// FileServiceExtractArchiveProcedure is the fully-qualified name of the FileService's
	// ExtractArchive RPC.
	FileServiceExtractArchiveProcedure = "/mineserver.v1.FileService/ExtractArchive"
	// FileServiceCreateFolderProcedure is the fully-qualified name of the FileService's CreateFolder
	// RPC.
	FileServiceCreateFolderProcedure = "/mineserver.v1.FileService/CreateFolder"
	// FileServiceMoveFileProcedure is the fully-qualified name of the FileService's MoveFile RPC.
	FileServiceMoveFileProcedure = "/mineserver.v1.FileService/MoveFile"
	// FileServiceCopyFileProcedure is the fully-qualified name of the FileService's CopyFile RPC.
	FileServiceCopyFileProcedure = "/mineserver.v1.FileService/CopyFile"
	// FileServiceCreateArchiveProcedure is the fully-qualified name of the FileService's CreateArchive
	// RPC.
	FileServiceCreateArchiveProcedure = "/mineserver.v1.FileService/CreateArchive"
	// FileServiceDownloadArchiveProcedure is the fully-qualified name of the FileService's
	// DownloadArchive RPC.
	FileServiceDownloadArchiveProcedure = "/mineserver.v1.FileService/DownloadArchive"
	// FileServiceInitFileDownloadProcedure is the fully-qualified name of the FileService's
	// InitFileDownload RPC.
	FileServiceInitFileDownloadProcedure = "/mineserver.v1.FileService/InitFileDownload"
	// FileServiceGetExtractionStatusProcedure is the fully-qualified name of the FileService's
	// GetExtractionStatus RPC.
	FileServiceGetExtractionStatusProcedure = "/mineserver.v1.FileService/GetExtractionStatus"
	// FileServiceDownloadRemoteArchiveProcedure is the fully-qualified name of the FileService's
	// DownloadRemoteArchive RPC.
	FileServiceDownloadRemoteArchiveProcedure = "/mineserver.v1.FileService/DownloadRemoteArchive"
	// FileServiceGetRemoteArchiveProgressProcedure is the fully-qualified name of the FileService's
	// GetRemoteArchiveProgress RPC.
	FileServiceGetRemoteArchiveProgressProcedure = "/mineserver.v1.FileService/GetRemoteArchiveProgress"
)

// FileServiceClient is a client for the mineserver.v1.FileService service.
type FileServiceClient interface {
	// Browse server directory
	ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error)
	// Download file content
	GetFile(context.Context, *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error)
	// Save an uploaded file
	SaveUploadedFile(context.Context, *connect.Request[v1.SaveUploadedFileRequest]) (*connect.Response[v1.SaveUploadedFileResponse], error)
	// Modify file content
	UpdateFile(context.Context, *connect.Request[v1.UpdateFileRequest]) (*connect.Response[v1.UpdateFileResponse], error)
	// Remove file or directory
	DeleteFile(context.Context, *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.DeleteFileResponse], error)
	// Change file name
	RenameFile(context.Context, *connect.Request[v1.RenameFileRequest]) (*connect.Response[v1.RenameFileResponse], error)
	// Unzip archive file
	ExtractArchive(context.Context, *connect.Request[v1.ExtractArchiveRequest]) (*connect.Response[v1.ExtractArchiveResponse], error)
	// Create a new folder
	CreateFolder(context.Context, *connect.Request[v1.CreateFolderRequest]) (*connect.Response[v1.CreateFolderResponse], error)
	// Move a file or directory
	MoveFile(context.Context, *connect.Request[v1.MoveFileRequest]) (*connect.Response[v1.MoveFileResponse], error)
	// Copy a file or directory
	CopyFile(context.Context, *connect.Request[v1.CopyFileRequest]) (*connect.Response[v1.CopyFileResponse], error)
	// Create a zip archive from selected paths
	CreateArchive(context.Context, *connect.Request[v1.CreateArchiveRequest]) (*connect.Response[v1.CreateArchiveResponse], error)
	// Download multiple files/folders as a zip
	DownloadArchive(context.Context, *connect.Request[v1.DownloadArchiveRequest]) (*connect.Response[v1.DownloadArchiveResponse], error)
	// Initiate a single-file download session (actual bytes served via GET /api/v1/download/{session_id})
	InitFileDownload(context.Context, *connect.Request[v1.InitFileDownloadRequest]) (*connect.Response[v1.InitFileDownloadResponse], error)
	// Poll extraction progress
	GetExtractionStatus(context.Context, *connect.Request[v1.GetExtractionStatusRequest]) (*connect.Response[v1.GetExtractionStatusResponse], error)
	// Download archive from remote URL (GitHub Releases, CDN, S3) with SHA256 verification and auto-extraction
	DownloadRemoteArchive(context.Context, *connect.Request[v1.DownloadRemoteArchiveRequest]) (*connect.Response[v1.DownloadRemoteArchiveResponse], error)
	// Poll remote archive download progress
	GetRemoteArchiveProgress(context.Context, *connect.Request[v1.GetRemoteArchiveProgressRequest]) (*connect.Response[v1.GetRemoteArchiveProgressResponse], error)
}

// NewFileServiceClient constructs a client for the mineserver.v1.FileService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFileServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fileServiceMethods := v1.File_mineserver_v1_file_proto.Services().ByName("FileService").Methods()
	return &fileServiceClient{
		listFiles: connect.NewClient[v1.ListFilesRequest, v1.ListFilesResponse](
			httpClient,
			baseURL+FileServiceListFilesProcedure,
			connect.WithSchema(fileServiceMethods.ByName("ListFiles")),
			connect.WithClientOptions(opts...),
		),
		getFile: connect.NewClient[v1.GetFileRequest, v1.GetFileResponse](
			httpClient,
			baseURL+FileServiceGetFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("GetFile")),
			connect.WithClientOptions(opts...),
		),
		saveUploadedFile: connect.NewClient[v1.SaveUploadedFileRequest, v1.SaveUploadedFileResponse](
			httpClient,
			baseURL+FileServiceSaveUploadedFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("SaveUploadedFile")),
			connect.WithClientOptions(opts...),
		),
		updateFile: connect.NewClient[v1.UpdateFileRequest, v1.UpdateFileResponse](
			httpClient,
			baseURL+FileServiceUpdateFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("UpdateFile")),
			connect.WithClientOptions(opts...),
		),
		deleteFile: connect.NewClient[v1.DeleteFileRequest, v1.DeleteFileResponse](
			httpClient,
			baseURL+FileServiceDeleteFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("DeleteFile")),
			connect.WithClientOptions(opts...),
		),
		renameFile: connect.NewClient[v1.RenameFileRequest, v1.RenameFileResponse](
			httpClient,
			baseURL+FileServiceRenameFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("RenameFile")),
			connect.WithClientOptions(opts...),
		),
		extractArchive: connect.NewClient[v1.ExtractArchiveRequest, v1.ExtractArchiveResponse](
			httpClient,
			baseURL+FileServiceExtractArchiveProcedure,
			connect.WithSchema(fileServiceMethods.ByName("ExtractArchive")),
			connect.WithClientOptions(opts...),
		),
		createFolder: connect.NewClient[v1.CreateFolderRequest, v1.CreateFolderResponse](
			httpClient,
			baseURL+FileServiceCreateFolderProcedure,
			connect.WithSchema(fileServiceMethods.ByName("CreateFolder")),
			connect.WithClientOptions(opts...),
		),
		moveFile: connect.NewClient[v1.MoveFileRequest, v1.MoveFileResponse](
			httpClient,
			baseURL+FileServiceMoveFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("MoveFile")),
			connect.WithClientOptions(opts...),
		),
		copyFile: connect.NewClient[v1.CopyFileRequest, v1.CopyFileResponse](
			httpClient,
			baseURL+FileServiceCopyFileProcedure,
			connect.WithSchema(fileServiceMethods.ByName("CopyFile")),
			connect.WithClientOptions(opts...),
		),
		createArchive: connect.NewClient[v1.CreateArchiveRequest, v1.CreateArchiveResponse](
			httpClient,
			baseURL+FileServiceCreateArchiveProcedure,
			connect.WithSchema(fileServiceMethods.ByName("CreateArchive")),
			connect.WithClientOptions(opts...),
		),
		downloadArchive: connect.NewClient[v1.DownloadArchiveRequest, v1.DownloadArchiveResponse](
			httpClient,
			baseURL+FileServiceDownloadArchiveProcedure,
			connect.WithSchema(fileServiceMethods.ByName("DownloadArchive")),
			connect.WithClientOptions(opts...),
		),
		initFileDownload: connect.NewClient[v1.InitFileDownloadRequest, v1.InitFileDownloadResponse](
			httpClient,
			baseURL+FileServiceInitFileDownloadProcedure,
			connect.WithSchema(fileServiceMethods.ByName("InitFileDownload")),
			connect.WithClientOptions(opts...),
		),
		getExtractionStatus: connect.NewClient[v1.GetExtractionStatusRequest, v1.GetExtractionStatusResponse](
			httpClient,
			baseURL+FileServiceGetExtractionStatusProcedure,
			connect.WithSchema(fileServiceMethods.ByName("GetExtractionStatus")),
			connect.WithClientOptions(opts...),
		),
		downloadRemoteArchive: connect.NewClient[v1.DownloadRemoteArchiveRequest, v1.DownloadRemoteArchiveResponse](
			httpClient,
			baseURL+FileServiceDownloadRemoteArchiveProcedure,
			connect.WithSchema(fileServiceMethods.ByName("DownloadRemoteArchive")),
			connect.WithClientOptions(opts...),
		),
		getRemoteArchiveProgress: connect.NewClient[v1.GetRemoteArchiveProgressRequest, v1.GetRemoteArchiveProgressResponse](
			httpClient,
			baseURL+FileServiceGetRemoteArchiveProgressProcedure,
			connect.WithSchema(fileServiceMethods.ByName("GetRemoteArchiveProgress")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fileServiceClient implements FileServiceClient.
type fileServiceClient struct {
	listFiles                *connect.Client[v1.ListFilesRequest, v1.ListFilesResponse]
	getFile                  *connect.Client[v1.GetFileRequest, v1.GetFileResponse]
	saveUploadedFile         *connect.Client[v1.SaveUploadedFileRequest, v1.SaveUploadedFileResponse]
	updateFile               *connect.Client[v1.UpdateFileRequest, v1.UpdateFileResponse]
	deleteFile               *connect.Client[v1.DeleteFileRequest, v1.DeleteFileResponse]
	renameFile               *connect.Client[v1.RenameFileRequest, v1.RenameFileResponse]
	extractArchive           *connect.Client[v1.ExtractArchiveRequest, v1.ExtractArchiveResponse]
	createFolder             *connect.Client[v1.CreateFolderRequest, v1.CreateFolderResponse]
	moveFile                 *connect.Client[v1.MoveFileRequest, v1.MoveFileResponse]
	copyFile                 *connect.Client[v1.CopyFileRequest, v1.CopyFileResponse]
	createArchive            *connect.Client[v1.CreateArchiveRequest, v1.CreateArchiveResponse]
	downloadArchive          *connect.Client[v1.DownloadArchiveRequest, v1.DownloadArchiveResponse]
	initFileDownload         *connect.Client[v1.InitFileDownloadRequest, v1.InitFileDownloadResponse]
	getExtractionStatus      *connect.Client[v1.GetExtractionStatusRequest, v1.GetExtractionStatusResponse]
	downloadRemoteArchive    *connect.Client[v1.DownloadRemoteArchiveRequest, v1.DownloadRemoteArchiveResponse]
	getRemoteArchiveProgress *connect.Client[v1.GetRemoteArchiveProgressRequest, v1.GetRemoteArchiveProgressResponse]
}

// ListFiles calls mineserver.v1.FileService.ListFiles.
func (c *fileServiceClient) ListFiles(ctx context.Context, req *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error) {
	return c.listFiles.CallUnary(ctx, req)
}

// GetFile calls mineserver.v1.FileService.GetFile.
func (c *fileServiceClient) GetFile(ctx context.Context, req *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error) {
	return c.getFile.CallUnary(ctx, req)
}

// SaveUploadedFile calls mineserver.v1.FileService.SaveUploadedFile.
func (c *fileServiceClient) SaveUploadedFile(ctx context.Context, req *connect.Request[v1.SaveUploadedFileRequest]) (*connect.Response[v1.SaveUploadedFileResponse], error) {
	return c.saveUploadedFile.CallUnary(ctx, req)
}

// UpdateFile calls mineserver.v1.FileService.UpdateFile.
func (c *fileServiceClient) UpdateFile(ctx context.Context, req *connect.Request[v1.UpdateFileRequest]) (*connect.Response[v1.UpdateFileResponse], error) {
	return c.updateFile.CallUnary(ctx, req)
}

// DeleteFile calls mineserver.v1.FileService.DeleteFile.
func (c *fileServiceClient) DeleteFile(ctx context.Context, req *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.DeleteFileResponse], error) {
	return c.deleteFile.CallUnary(ctx, req)
}

// RenameFile calls mineserver.v1.FileService.RenameFile.
func (c *fileServiceClient) RenameFile(ctx context.Context, req *connect.Request[v1.RenameFileRequest]) (*connect.Response[v1.RenameFileResponse], error) {
	return c.renameFile.CallUnary(ctx, req)
}

// ExtractArchive calls mineserver.v1.FileService.ExtractArchive.
func (c *fileServiceClient) ExtractArchive(ctx context.Context, req *connect.Request[v1.ExtractArchiveRequest]) (*connect.Response[v1.ExtractArchiveResponse], error) {
	return c.extractArchive.CallUnary(ctx, req)
}

// CreateFolder calls mineserver.v1.FileService.CreateFolder.
func (c *fileServiceClient) CreateFolder(ctx context.Context, req *connect.Request[v1.CreateFolderRequest]) (*connect.Response[v1.CreateFolderResponse], error) {
	return c.createFolder.CallUnary(ctx, req)
}

// MoveFile calls mineserver.v1.FileService.MoveFile.
func (c *fileServiceClient) MoveFile(ctx context.Context, req *connect.Request[v1.MoveFileRequest]) (*connect.Response[v1.MoveFileResponse], error) {
	return c.moveFile.CallUnary(ctx, req)
}

// CopyFile calls mineserver.v1.FileService.CopyFile.
func (c *fileServiceClient) CopyFile(ctx context.Context, req *connect.Request[v1.CopyFileRequest]) (*connect.Response[v1.CopyFileResponse], error) {
	return c.copyFile.CallUnary(ctx, req)
}

// CreateArchive calls mineserver.v1.FileService.CreateArchive.
func (c *fileServiceClient) CreateArchive(ctx context.Context, req *connect.Request[v1.CreateArchiveRequest]) (*connect.Response[v1.CreateArchiveResponse], error) {
	return c.createArchive.CallUnary(ctx, req)
}

// DownloadArchive calls mineserver.v1.FileService.DownloadArchive.
func (c *fileServiceClient) DownloadArchive(ctx context.Context, req *connect.Request[v1.DownloadArchiveRequest]) (*connect.Response[v1.DownloadArchiveResponse], error) {
	return c.downloadArchive.CallUnary(ctx, req)
}

// InitFileDownload calls mineserver.v1.FileService.InitFileDownload.
func (c *fileServiceClient) InitFileDownload(ctx context.Context, req *connect.Request[v1.InitFileDownloadRequest]) (*connect.Response[v1.InitFileDownloadResponse], error) {
	return c.initFileDownload.CallUnary(ctx, req)
}

// GetExtractionStatus calls mineserver.v1.FileService.GetExtractionStatus.
func (c *fileServiceClient) GetExtractionStatus(ctx context.Context, req *connect.Request[v1.GetExtractionStatusRequest]) (*connect.Response[v1.GetExtractionStatusResponse], error) {
	return c.getExtractionStatus.CallUnary(ctx, req)
}

// DownloadRemoteArchive calls mineserver.v1.FileService.DownloadRemoteArchive.
func (c *fileServiceClient) DownloadRemoteArchive(ctx context.Context, req *connect.Request[v1.DownloadRemoteArchiveRequest]) (*connect.Response[v1.DownloadRemoteArchiveResponse], error) {
	return c.downloadRemoteArchive.CallUnary(ctx, req)
}

// GetRemoteArchiveProgress calls mineserver.v1.FileService.GetRemoteArchiveProgress.
func (c *fileServiceClient) GetRemoteArchiveProgress(ctx context.Context, req *connect.Request[v1.GetRemoteArchiveProgressRequest]) (*connect.Response[v1.GetRemoteArchiveProgressResponse], error) {
	return c.getRemoteArchiveProgress.CallUnary(ctx, req)
}

// FileServiceHandler is an implementation of the mineserver.v1.FileService service.
type FileServiceHandler interface {
	// Browse server directory
	ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error)
	// Download file content
	GetFile(context.Context, *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error)
	// Save an uploaded file
	SaveUploadedFile(context.Context, *connect.Request[v1.SaveUploadedFileRequest]) (*connect.Response[v1.SaveUploadedFileResponse], error)
	// Modify file content
	UpdateFile(context.Context, *connect.Request[v1.UpdateFileRequest]) (*connect.Response[v1.UpdateFileResponse], error)
	// Remove file or directory
	DeleteFile(context.Context, *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.DeleteFileResponse], error)
	// Change file name
	RenameFile(context.Context, *connect.Request[v1.RenameFileRequest]) (*connect.Response[v1.RenameFileResponse], error)
	// Unzip archive file
	ExtractArchive(context.Context, *connect.Request[v1.ExtractArchiveRequest]) (*connect.Response[v1.ExtractArchiveResponse], error)
	// Create a new folder
	CreateFolder(context.Context, *connect.Request[v1.CreateFolderRequest]) (*connect.Response[v1.CreateFolderResponse], error)
	// Move a file or directory
	MoveFile(context.Context, *connect.Request[v1.MoveFileRequest]) (*connect.Response[v1.MoveFileResponse], error)
	// Copy a file or directory
	CopyFile(context.Context, *connect.Request[v1.CopyFileRequest]) (*connect.Response[v1.CopyFileResponse], error)
	// Create a zip archive from selected paths
	CreateArchive(context.Context, *connect.Request[v1.CreateArchiveRequest]) (*connect.Response[v1.CreateArchiveResponse], error)
	// Download multiple files/folders as a zip
	DownloadArchive(context.Context, *connect.Request[v1.DownloadArchiveRequest]) (*connect.Response[v1.DownloadArchiveResponse], error)
	// Initiate a single-file download session (actual bytes served via GET /api/v1/download/{session_id})
	InitFileDownload(context.Context, *connect.Request[v1.InitFileDownloadRequest]) (*connect.Response[v1.InitFileDownloadResponse], error)
	// Poll extraction progress
	GetExtractionStatus(context.Context, *connect.Request[v1.GetExtractionStatusRequest]) (*connect.Response[v1.GetExtractionStatusResponse], error)
	// Download archive from remote URL (GitHub Releases, CDN, S3) with SHA256 verification and auto-extraction
	DownloadRemoteArchive(context.Context, *connect.Request[v1.DownloadRemoteArchiveRequest]) (*connect.Response[v1.DownloadRemoteArchiveResponse], error)
	// Poll remote archive download progress
	GetRemoteArchiveProgress(context.Context, *connect.Request[v1.GetRemoteArchiveProgressRequest]) (*connect.Response[v1.GetRemoteArchiveProgressResponse], error)
}

// NewFileServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFileServiceHandler(svc FileServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fileServiceMethods := v1.File_mineserver_v1_file_proto.Services().ByName("FileService").Methods()
	fileServiceListFilesHandler := connect.NewUnaryHandler(
		FileServiceListFilesProcedure,
		svc.ListFiles,
		connect.WithSchema(fileServiceMethods.ByName("ListFiles")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceGetFileHandler := connect.NewUnaryHandler(
		FileServiceGetFileProcedure,
		svc.GetFile,
		connect.WithSchema(fileServiceMethods.ByName("GetFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceSaveUploadedFileHandler := connect.NewUnaryHandler(
		FileServiceSaveUploadedFileProcedure,
		svc.SaveUploadedFile,
		connect.WithSchema(fileServiceMethods.ByName("SaveUploadedFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceUpdateFileHandler := connect.NewUnaryHandler(
		FileServiceUpdateFileProcedure,
		svc.UpdateFile,
		connect.WithSchema(fileServiceMethods.ByName("UpdateFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDeleteFileHandler := connect.NewUnaryHandler(
		FileServiceDeleteFileProcedure,
		svc.DeleteFile,
		connect.WithSchema(fileServiceMethods.ByName("DeleteFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceRenameFileHandler := connect.NewUnaryHandler(
		FileServiceRenameFileProcedure,
		svc.RenameFile,
		connect.WithSchema(fileServiceMethods.ByName("RenameFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceExtractArchiveHandler := connect.NewUnaryHandler(
		FileServiceExtractArchiveProcedure,
		svc.ExtractArchive,
		connect.WithSchema(fileServiceMethods.ByName("ExtractArchive")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceCreateFolderHandler := connect.NewUnaryHandler(
		FileServiceCreateFolderProcedure,
		svc.CreateFolder,
		connect.WithSchema(fileServiceMethods.ByName("CreateFolder")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceMoveFileHandler := connect.NewUnaryHandler(
		FileServiceMoveFileProcedure,
		svc.MoveFile,
		connect.WithSchema(fileServiceMethods.ByName("MoveFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceCopyFileHandler := connect.NewUnaryHandler(
		FileServiceCopyFileProcedure,
		svc.CopyFile,
		connect.WithSchema(fileServiceMethods.ByName("CopyFile")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceCreateArchiveHandler := connect.NewUnaryHandler(
		FileServiceCreateArchiveProcedure,
		svc.CreateArchive,
		connect.WithSchema(fileServiceMethods.ByName("CreateArchive")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDownloadArchiveHandler := connect.NewUnaryHandler(
		FileServiceDownloadArchiveProcedure,
		svc.DownloadArchive,
		connect.WithSchema(fileServiceMethods.ByName("DownloadArchive")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceInitFileDownloadHandler := connect.NewUnaryHandler(
		FileServiceInitFileDownloadProcedure,
		svc.InitFileDownload,
		connect.WithSchema(fileServiceMethods.ByName("InitFileDownload")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceGetExtractionStatusHandler := connect.NewUnaryHandler(
		FileServiceGetExtractionStatusProcedure,
		svc.GetExtractionStatus,
		connect.WithSchema(fileServiceMethods.ByName("GetExtractionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceDownloadRemoteArchiveHandler := connect.NewUnaryHandler(
		FileServiceDownloadRemoteArchiveProcedure,
		svc.DownloadRemoteArchive,
		connect.WithSchema(fileServiceMethods.ByName("DownloadRemoteArchive")),
		connect.WithHandlerOptions(opts...),
	)
	fileServiceGetRemoteArchiveProgressHandler := connect.NewUnaryHandler(
		FileServiceGetRemoteArchiveProgressProcedure,
		svc.GetRemoteArchiveProgress,
		connect.WithSchema(fileServiceMethods.ByName("GetRemoteArchiveProgress")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mineserver.v1.FileService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FileServiceListFilesProcedure:
			fileServiceListFilesHandler.ServeHTTP(w, r)
		case FileServiceGetFileProcedure:
			fileServiceGetFileHandler.ServeHTTP(w, r)
		case FileServiceSaveUploadedFileProcedure:
			fileServiceSaveUploadedFileHandler.ServeHTTP(w, r)
		case FileServiceUpdateFileProcedure:
			fileServiceUpdateFileHandler.ServeHTTP(w, r)
		case FileServiceDeleteFileProcedure:
			fileServiceDeleteFileHandler.ServeHTTP(w, r)
		case FileServiceRenameFileProcedure:
			fileServiceRenameFileHandler.ServeHTTP(w, r)
		case FileServiceExtractArchiveProcedure:
			fileServiceExtractArchiveHandler.ServeHTTP(w, r)
		case FileServiceCreateFolderProcedure:
			fileServiceCreateFolderHandler.ServeHTTP(w, r)
		case FileServiceMoveFileProcedure:
			fileServiceMoveFileHandler.ServeHTTP(w, r)
		case FileServiceCopyFileProcedure:
			fileServiceCopyFileHandler.ServeHTTP(w, r)
		case FileServiceCreateArchiveProcedure:
			fileServiceCreateArchiveHandler.ServeHTTP(w, r)
		case FileServiceDownloadArchiveProcedure:
			fileServiceDownloadArchiveHandler.ServeHTTP(w, r)
		case FileServiceInitFileDownloadProcedure:
			fileServiceInitFileDownloadHandler.ServeHTTP(w, r)
		case FileServiceGetExtractionStatusProcedure:
			fileServiceGetExtractionStatusHandler.ServeHTTP(w, r)
		case FileServiceDownloadRemoteArchiveProcedure:
			fileServiceDownloadRemoteArchiveHandler.ServeHTTP(w, r)
		case FileServiceGetRemoteArchiveProgressProcedure:
			fileServiceGetRemoteArchiveProgressHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFileServiceHandler struct{}

func (UnimplementedFileServiceHandler) ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.ListFiles is not implemented"))
}

func (UnimplementedFileServiceHandler) GetFile(context.Context, *connect.Request[v1.GetFileRequest]) (*connect.Response[v1.GetFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.GetFile is not implemented"))
}

func (UnimplementedFileServiceHandler) SaveUploadedFile(context.Context, *connect.Request[v1.SaveUploadedFileRequest]) (*connect.Response[v1.SaveUploadedFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.SaveUploadedFile is not implemented"))
}

func (UnimplementedFileServiceHandler) UpdateFile(context.Context, *connect.Request[v1.UpdateFileRequest]) (*connect.Response[v1.UpdateFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.UpdateFile is not implemented"))
}

func (UnimplementedFileServiceHandler) DeleteFile(context.Context, *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.DeleteFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.DeleteFile is not implemented"))
}

func (UnimplementedFileServiceHandler) RenameFile(context.Context, *connect.Request[v1.RenameFileRequest]) (*connect.Response[v1.RenameFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.RenameFile is not implemented"))
}

func (UnimplementedFileServiceHandler) ExtractArchive(context.Context, *connect.Request[v1.ExtractArchiveRequest]) (*connect.Response[v1.ExtractArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.ExtractArchive is not implemented"))
}

func (UnimplementedFileServiceHandler) CreateFolder(context.Context, *connect.Request[v1.CreateFolderRequest]) (*connect.Response[v1.CreateFolderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.CreateFolder is not implemented"))
}

func (UnimplementedFileServiceHandler) MoveFile(context.Context, *connect.Request[v1.MoveFileRequest]) (*connect.Response[v1.MoveFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.MoveFile is not implemented"))
}

func (UnimplementedFileServiceHandler) CopyFile(context.Context, *connect.Request[v1.CopyFileRequest]) (*connect.Response[v1.CopyFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.CopyFile is not implemented"))
}

func (UnimplementedFileServiceHandler) CreateArchive(context.Context, *connect.Request[v1.CreateArchiveRequest]) (*connect.Response[v1.CreateArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.CreateArchive is not implemented"))
}

func (UnimplementedFileServiceHandler) DownloadArchive(context.Context, *connect.Request[v1.DownloadArchiveRequest]) (*connect.Response[v1.DownloadArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.DownloadArchive is not implemented"))
}

func (UnimplementedFileServiceHandler) InitFileDownload(context.Context, *connect.Request[v1.InitFileDownloadRequest]) (*connect.Response[v1.InitFileDownloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.InitFileDownload is not implemented"))
}

func (UnimplementedFileServiceHandler) GetExtractionStatus(context.Context, *connect.Request[v1.GetExtractionStatusRequest]) (*connect.Response[v1.GetExtractionStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.GetExtractionStatus is not implemented"))
}

func (UnimplementedFileServiceHandler) DownloadRemoteArchive(context.Context, *connect.Request[v1.DownloadRemoteArchiveRequest]) (*connect.Response[v1.DownloadRemoteArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.DownloadRemoteArchive is not implemented"))
}

func (UnimplementedFileServiceHandler) GetRemoteArchiveProgress(context.Context, *connect.Request[v1.GetRemoteArchiveProgressRequest]) (*connect.Response[v1.GetRemoteArchiveProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.FileService.GetRemoteArchiveProgress is not implemented"))
}
