// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mineserver/v1/task.proto

package mineserverv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/athNdev/mineserver/pkg/proto/mineserver/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TaskServiceName is the fully-qualified name of the TaskService service.
	TaskServiceName = "mineserver.v1.TaskService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TaskServiceListTasksProcedure is the fully-qualified name of the TaskService's ListTasks RPC.
	TaskServiceListTasksProcedure = "/mineserver.v1.TaskService/ListTasks"
	// TaskServiceGetTaskProcedure is the fully-qualified name of the TaskService's GetTask RPC.
	TaskServiceGetTaskProcedure = "/mineserver.v1.TaskService/GetTask"
	// TaskServiceCreateTaskProcedure is the fully-qualified name of the TaskService's CreateTask RPC.
	TaskServiceCreateTaskProcedure = "/mineserver.v1.TaskService/CreateTask"
	// TaskServiceUpdateTaskProcedure is the fully-qualified name of the TaskService's UpdateTask RPC.
	TaskServiceUpdateTaskProcedure = "/mineserver.v1.TaskService/UpdateTask"
	// TaskServiceDeleteTaskProcedure is the fully-qualified name of the TaskService's DeleteTask RPC.
	TaskServiceDeleteTaskProcedure = "/mineserver.v1.TaskService/DeleteTask"
	// TaskServiceToggleTaskProcedure is the fully-qualified name of the TaskService's ToggleTask RPC.
	TaskServiceToggleTaskProcedure = "/mineserver.v1.TaskService/ToggleTask"
	// TaskServiceTriggerTaskProcedure is the fully-qualified name of the TaskService's TriggerTask RPC.
	TaskServiceTriggerTaskProcedure = "/mineserver.v1.TaskService/TriggerTask"
	// TaskServiceListTaskExecutionsProcedure is the fully-qualified name of the TaskService's
	// ListTaskExecutions RPC.
	TaskServiceListTaskExecutionsProcedure = "/mineserver.v1.TaskService/ListTaskExecutions"
	// TaskServiceListServerExecutionsProcedure is the fully-qualified name of the TaskService's
	// ListServerExecutions RPC.
	TaskServiceListServerExecutionsProcedure = "/mineserver.v1.TaskService/ListServerExecutions"
	// TaskServiceGetTaskExecutionProcedure is the fully-qualified name of the TaskService's
	// GetTaskExecution RPC.
	TaskServiceGetTaskExecutionProcedure = "/mineserver.v1.TaskService/GetTaskExecution"
	// TaskServiceCancelExecutionProcedure is the fully-qualified name of the TaskService's
	// CancelExecution RPC.
	TaskServiceCancelExecutionProcedure = "/mineserver.v1.TaskService/CancelExecution"
	// TaskServiceGetSchedulerStatusProcedure is the fully-qualified name of the TaskService's
	// GetSchedulerStatus RPC.
	TaskServiceGetSchedulerStatusProcedure = "/mineserver.v1.TaskService/GetSchedulerStatus"
)

// TaskServiceClient is a client for the mineserver.v1.TaskService service.
type TaskServiceClient interface {
	// List all tasks for a server
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	// Get a specific task
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	// Create a new scheduled task
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	// Update an existing task
	UpdateTask(context.Context, *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error)
	// Delete a task
	DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error)
	// Toggle task enabled/disabled status
	ToggleTask(context.Context, *connect.Request[v1.ToggleTaskRequest]) (*connect.Response[v1.ToggleTaskResponse], error)
	// Manually trigger a task execution
	TriggerTask(context.Context, *connect.Request[v1.TriggerTaskRequest]) (*connect.Response[v1.TriggerTaskResponse], error)
	// Get execution history for a task
	ListTaskExecutions(context.Context, *connect.Request[v1.ListTaskExecutionsRequest]) (*connect.Response[v1.ListTaskExecutionsResponse], error)
	// Get execution history for a server
	ListServerExecutions(context.Context, *connect.Request[v1.ListServerExecutionsRequest]) (*connect.Response[v1.ListServerExecutionsResponse], error)
	// Get a specific execution
	GetTaskExecution(context.Context, *connect.Request[v1.GetTaskExecutionRequest]) (*connect.Response[v1.GetTaskExecutionResponse], error)
	// Cancel a running execution
	CancelExecution(context.Context, *connect.Request[v1.CancelExecutionRequest]) (*connect.Response[v1.CancelExecutionResponse], error)
	// Get scheduler status
	GetSchedulerStatus(context.Context, *connect.Request[v1.GetSchedulerStatusRequest]) (*connect.Response[v1.GetSchedulerStatusResponse], error)
}

// NewTaskServiceClient constructs a client for the mineserver.v1.TaskService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTaskServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TaskServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	taskServiceMethods := v1.File_mineserver_v1_task_proto.Services().ByName("TaskService").Methods()
	return &taskServiceClient{
		listTasks: connect.NewClient[v1.ListTasksRequest, v1.ListTasksResponse](
			httpClient,
			baseURL+TaskServiceListTasksProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+TaskServiceGetTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[v1.CreateTaskRequest, v1.CreateTaskResponse](
			httpClient,
			baseURL+TaskServiceCreateTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		updateTask: connect.NewClient[v1.UpdateTaskRequest, v1.UpdateTaskResponse](
			httpClient,
			baseURL+TaskServiceUpdateTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("UpdateTask")),
			connect.WithClientOptions(opts...),
		),
		deleteTask: connect.NewClient[v1.DeleteTaskRequest, v1.DeleteTaskResponse](
			httpClient,
			baseURL+TaskServiceDeleteTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("DeleteTask")),
			connect.WithClientOptions(opts...),
		),
		toggleTask: connect.NewClient[v1.ToggleTaskRequest, v1.ToggleTaskResponse](
			httpClient,
			baseURL+TaskServiceToggleTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ToggleTask")),
			connect.WithClientOptions(opts...),
		),
		triggerTask: connect.NewClient[v1.TriggerTaskRequest, v1.TriggerTaskResponse](
			httpClient,
			baseURL+TaskServiceTriggerTaskProcedure,
			connect.WithSchema(taskServiceMethods.ByName("TriggerTask")),
			connect.WithClientOptions(opts...),
		),
		listTaskExecutions: connect.NewClient[v1.ListTaskExecutionsRequest, v1.ListTaskExecutionsResponse](
			httpClient,
			baseURL+TaskServiceListTaskExecutionsProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ListTaskExecutions")),
			connect.WithClientOptions(opts...),
		),
		listServerExecutions: connect.NewClient[v1.ListServerExecutionsRequest, v1.ListServerExecutionsResponse](
			httpClient,
			baseURL+TaskServiceListServerExecutionsProcedure,
			connect.WithSchema(taskServiceMethods.ByName("ListServerExecutions")),
			connect.WithClientOptions(opts...),
		),
		getTaskExecution: connect.NewClient[v1.GetTaskExecutionRequest, v1.GetTaskExecutionResponse](
			httpClient,
			baseURL+TaskServiceGetTaskExecutionProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetTaskExecution")),
			connect.WithClientOptions(opts...),
		),
		cancelExecution: connect.NewClient[v1.CancelExecutionRequest, v1.CancelExecutionResponse](
			httpClient,
			baseURL+TaskServiceCancelExecutionProcedure,
			connect.WithSchema(taskServiceMethods.ByName("CancelExecution")),
			connect.WithClientOptions(opts...),
		),
		getSchedulerStatus: connect.NewClient[v1.GetSchedulerStatusRequest, v1.GetSchedulerStatusResponse](
			httpClient,
			baseURL+TaskServiceGetSchedulerStatusProcedure,
			connect.WithSchema(taskServiceMethods.ByName("GetSchedulerStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// taskServiceClient implements TaskServiceClient.
type taskServiceClient struct {
	listTasks            *connect.Client[v1.ListTasksRequest, v1.ListTasksResponse]
	getTask              *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
	createTask           *connect.Client[v1.CreateTaskRequest, v1.CreateTaskResponse]
	updateTask           *connect.Client[v1.UpdateTaskRequest, v1.UpdateTaskResponse]
	deleteTask           *connect.Client[v1.DeleteTaskRequest, v1.DeleteTaskResponse]
	toggleTask           *connect.Client[v1.ToggleTaskRequest, v1.ToggleTaskResponse]
	triggerTask          *connect.Client[v1.TriggerTaskRequest, v1.TriggerTaskResponse]
	listTaskExecutions   *connect.Client[v1.ListTaskExecutionsRequest, v1.ListTaskExecutionsResponse]
	listServerExecutions *connect.Client[v1.ListServerExecutionsRequest, v1.ListServerExecutionsResponse]
	getTaskExecution     *connect.Client[v1.GetTaskExecutionRequest, v1.GetTaskExecutionResponse]
	cancelExecution      *connect.Client[v1.CancelExecutionRequest, v1.CancelExecutionResponse]
	getSchedulerStatus   *connect.Client[v1.GetSchedulerStatusRequest, v1.GetSchedulerStatusResponse]
}

// ListTasks calls mineserver.v1.TaskService.ListTasks.
func (c *taskServiceClient) ListTasks(ctx context.Context, req *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// GetTask calls mineserver.v1.TaskService.GetTask.
func (c *taskServiceClient) GetTask(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// CreateTask calls mineserver.v1.TaskService.CreateTask.
func (c *taskServiceClient) CreateTask(ctx context.Context, req *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// UpdateTask calls mineserver.v1.TaskService.UpdateTask.
func (c *taskServiceClient) UpdateTask(ctx context.Context, req *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error) {
	return c.updateTask.CallUnary(ctx, req)
}

// DeleteTask calls mineserver.v1.TaskService.DeleteTask.
func (c *taskServiceClient) DeleteTask(ctx context.Context, req *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	return c.deleteTask.CallUnary(ctx, req)
}

// ToggleTask calls mineserver.v1.TaskService.ToggleTask.
func (c *taskServiceClient) ToggleTask(ctx context.Context, req *connect.Request[v1.ToggleTaskRequest]) (*connect.Response[v1.ToggleTaskResponse], error) {
	return c.toggleTask.CallUnary(ctx, req)
}

// TriggerTask calls mineserver.v1.TaskService.TriggerTask.
func (c *taskServiceClient) TriggerTask(ctx context.Context, req *connect.Request[v1.TriggerTaskRequest]) (*connect.Response[v1.TriggerTaskResponse], error) {
	return c.triggerTask.CallUnary(ctx, req)
}

// ListTaskExecutions calls mineserver.v1.TaskService.ListTaskExecutions.
func (c *taskServiceClient) ListTaskExecutions(ctx context.Context, req *connect.Request[v1.ListTaskExecutionsRequest]) (*connect.Response[v1.ListTaskExecutionsResponse], error) {
	return c.listTaskExecutions.CallUnary(ctx, req)
}

// ListServerExecutions calls mineserver.v1.TaskService.ListServerExecutions.
func (c *taskServiceClient) ListServerExecutions(ctx context.Context, req *connect.Request[v1.ListServerExecutionsRequest]) (*connect.Response[v1.ListServerExecutionsResponse], error) {
	return c.listServerExecutions.CallUnary(ctx, req)
}

// GetTaskExecution calls mineserver.v1.TaskService.GetTaskExecution.
func (c *taskServiceClient) GetTaskExecution(ctx context.Context, req *connect.Request[v1.GetTaskExecutionRequest]) (*connect.Response[v1.GetTaskExecutionResponse], error) {
	return c.getTaskExecution.CallUnary(ctx, req)
}

// CancelExecution calls mineserver.v1.TaskService.CancelExecution.
func (c *taskServiceClient) CancelExecution(ctx context.Context, req *connect.Request[v1.CancelExecutionRequest]) (*connect.Response[v1.CancelExecutionResponse], error) {
	return c.cancelExecution.CallUnary(ctx, req)
}

// GetSchedulerStatus calls mineserver.v1.TaskService.GetSchedulerStatus.
func (c *taskServiceClient) GetSchedulerStatus(ctx context.Context, req *connect.Request[v1.GetSchedulerStatusRequest]) (*connect.Response[v1.GetSchedulerStatusResponse], error) {
	return c.getSchedulerStatus.CallUnary(ctx, req)
}

// TaskServiceHandler is an implementation of the mineserver.v1.TaskService service.
type TaskServiceHandler interface {
	// List all tasks for a server
	ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error)
	// Get a specific task
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	// Create a new scheduled task
	CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error)
	// Update an existing task
	UpdateTask(context.Context, *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error)
	// Delete a task
	DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error)
	// Toggle task enabled/disabled status
	ToggleTask(context.Context, *connect.Request[v1.ToggleTaskRequest]) (*connect.Response[v1.ToggleTaskResponse], error)
	// Manually trigger a task execution
	TriggerTask(context.Context, *connect.Request[v1.TriggerTaskRequest]) (*connect.Response[v1.TriggerTaskResponse], error)
	// Get execution history for a task
	ListTaskExecutions(context.Context, *connect.Request[v1.ListTaskExecutionsRequest]) (*connect.Response[v1.ListTaskExecutionsResponse], error)
	// Get execution history for a server
	ListServerExecutions(context.Context, *connect.Request[v1.ListServerExecutionsRequest]) (*connect.Response[v1.ListServerExecutionsResponse], error)
	// Get a specific execution
	GetTaskExecution(context.Context, *connect.Request[v1.GetTaskExecutionRequest]) (*connect.Response[v1.GetTaskExecutionResponse], error)
	// Cancel a running execution
	CancelExecution(context.Context, *connect.Request[v1.CancelExecutionRequest]) (*connect.Response[v1.CancelExecutionResponse], error)
	// Get scheduler status
	GetSchedulerStatus(context.Context, *connect.Request[v1.GetSchedulerStatusRequest]) (*connect.Response[v1.GetSchedulerStatusResponse], error)
}

// NewTaskServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTaskServiceHandler(svc TaskServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	taskServiceMethods := v1.File_mineserver_v1_task_proto.Services().ByName("TaskService").Methods()
	taskServiceListTasksHandler := connect.NewUnaryHandler(
		TaskServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(taskServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(taskServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCreateTaskHandler := connect.NewUnaryHandler(
		TaskServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(taskServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceUpdateTaskHandler := connect.NewUnaryHandler(
		TaskServiceUpdateTaskProcedure,
		svc.UpdateTask,
		connect.WithSchema(taskServiceMethods.ByName("UpdateTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceDeleteTaskHandler := connect.NewUnaryHandler(
		TaskServiceDeleteTaskProcedure,
		svc.DeleteTask,
		connect.WithSchema(taskServiceMethods.ByName("DeleteTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceToggleTaskHandler := connect.NewUnaryHandler(
		TaskServiceToggleTaskProcedure,
		svc.ToggleTask,
		connect.WithSchema(taskServiceMethods.ByName("ToggleTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceTriggerTaskHandler := connect.NewUnaryHandler(
		TaskServiceTriggerTaskProcedure,
		svc.TriggerTask,
		connect.WithSchema(taskServiceMethods.ByName("TriggerTask")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceListTaskExecutionsHandler := connect.NewUnaryHandler(
		TaskServiceListTaskExecutionsProcedure,
		svc.ListTaskExecutions,
		connect.WithSchema(taskServiceMethods.ByName("ListTaskExecutions")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceListServerExecutionsHandler := connect.NewUnaryHandler(
		TaskServiceListServerExecutionsProcedure,
		svc.ListServerExecutions,
		connect.WithSchema(taskServiceMethods.ByName("ListServerExecutions")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetTaskExecutionHandler := connect.NewUnaryHandler(
		TaskServiceGetTaskExecutionProcedure,
		svc.GetTaskExecution,
		connect.WithSchema(taskServiceMethods.ByName("GetTaskExecution")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceCancelExecutionHandler := connect.NewUnaryHandler(
		TaskServiceCancelExecutionProcedure,
		svc.CancelExecution,
		connect.WithSchema(taskServiceMethods.ByName("CancelExecution")),
		connect.WithHandlerOptions(opts...),
	)
	taskServiceGetSchedulerStatusHandler := connect.NewUnaryHandler(
		TaskServiceGetSchedulerStatusProcedure,
		svc.GetSchedulerStatus,
		connect.WithSchema(taskServiceMethods.ByName("GetSchedulerStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mineserver.v1.TaskService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TaskServiceListTasksProcedure:
			taskServiceListTasksHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskProcedure:
			taskServiceGetTaskHandler.ServeHTTP(w, r)
		case TaskServiceCreateTaskProcedure:
			taskServiceCreateTaskHandler.ServeHTTP(w, r)
		case TaskServiceUpdateTaskProcedure:
			taskServiceUpdateTaskHandler.ServeHTTP(w, r)
		case TaskServiceDeleteTaskProcedure:
			taskServiceDeleteTaskHandler.ServeHTTP(w, r)
		case TaskServiceToggleTaskProcedure:
			taskServiceToggleTaskHandler.ServeHTTP(w, r)
		case TaskServiceTriggerTaskProcedure:
			taskServiceTriggerTaskHandler.ServeHTTP(w, r)
		case TaskServiceListTaskExecutionsProcedure:
			taskServiceListTaskExecutionsHandler.ServeHTTP(w, r)
		case TaskServiceListServerExecutionsProcedure:
			taskServiceListServerExecutionsHandler.ServeHTTP(w, r)
		case TaskServiceGetTaskExecutionProcedure:
			taskServiceGetTaskExecutionHandler.ServeHTTP(w, r)
		case TaskServiceCancelExecutionProcedure:
			taskServiceCancelExecutionHandler.ServeHTTP(w, r)
		case TaskServiceGetSchedulerStatusProcedure:
			taskServiceGetSchedulerStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTaskServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTaskServiceHandler struct{}

func (UnimplementedTaskServiceHandler) ListTasks(context.Context, *connect.Request[v1.ListTasksRequest]) (*connect.Response[v1.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.ListTasks is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.GetTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) CreateTask(context.Context, *connect.Request[v1.CreateTaskRequest]) (*connect.Response[v1.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.CreateTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) UpdateTask(context.Context, *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.UpdateTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) DeleteTask(context.Context, *connect.Request[v1.DeleteTaskRequest]) (*connect.Response[v1.DeleteTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.DeleteTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) ToggleTask(context.Context, *connect.Request[v1.ToggleTaskRequest]) (*connect.Response[v1.ToggleTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.ToggleTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) TriggerTask(context.Context, *connect.Request[v1.TriggerTaskRequest]) (*connect.Response[v1.TriggerTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.TriggerTask is not implemented"))
}

func (UnimplementedTaskServiceHandler) ListTaskExecutions(context.Context, *connect.Request[v1.ListTaskExecutionsRequest]) (*connect.Response[v1.ListTaskExecutionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.ListTaskExecutions is not implemented"))
}

func (UnimplementedTaskServiceHandler) ListServerExecutions(context.Context, *connect.Request[v1.ListServerExecutionsRequest]) (*connect.Response[v1.ListServerExecutionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.ListServerExecutions is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetTaskExecution(context.Context, *connect.Request[v1.GetTaskExecutionRequest]) (*connect.Response[v1.GetTaskExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.GetTaskExecution is not implemented"))
}

func (UnimplementedTaskServiceHandler) CancelExecution(context.Context, *connect.Request[v1.CancelExecutionRequest]) (*connect.Response[v1.CancelExecutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.CancelExecution is not implemented"))
}

func (UnimplementedTaskServiceHandler) GetSchedulerStatus(context.Context, *connect.Request[v1.GetSchedulerStatusRequest]) (*connect.Response[v1.GetSchedulerStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mineserver.v1.TaskService.GetSchedulerStatus is not implemented"))
}
