// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: carbonpanel/v1/minecraft.proto

package carbonpanelv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/athNdev/carbon-panel/pkg/proto/carbonpanel/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MinecraftServiceName is the fully-qualified name of the MinecraftService service.
	MinecraftServiceName = "carbonpanel.v1.MinecraftService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MinecraftServiceGetMinecraftVersionsProcedure is the fully-qualified name of the
	// MinecraftService's GetMinecraftVersions RPC.
	MinecraftServiceGetMinecraftVersionsProcedure = "/carbonpanel.v1.MinecraftService/GetMinecraftVersions"
	// MinecraftServiceGetModLoadersProcedure is the fully-qualified name of the MinecraftService's
	// GetModLoaders RPC.
	MinecraftServiceGetModLoadersProcedure = "/carbonpanel.v1.MinecraftService/GetModLoaders"
	// MinecraftServiceGetDockerImagesProcedure is the fully-qualified name of the MinecraftService's
	// GetDockerImages RPC.
	MinecraftServiceGetDockerImagesProcedure = "/carbonpanel.v1.MinecraftService/GetDockerImages"
)

// MinecraftServiceClient is a client for the carbonpanel.v1.MinecraftService service.
type MinecraftServiceClient interface {
	// List all Minecraft versions
	GetMinecraftVersions(context.Context, *connect.Request[v1.GetMinecraftVersionsRequest]) (*connect.Response[v1.GetMinecraftVersionsResponse], error)
	// List supported mod loaders
	GetModLoaders(context.Context, *connect.Request[v1.GetModLoadersRequest]) (*connect.Response[v1.GetModLoadersResponse], error)
	// List available Docker images
	GetDockerImages(context.Context, *connect.Request[v1.GetDockerImagesRequest]) (*connect.Response[v1.GetDockerImagesResponse], error)
}

// NewMinecraftServiceClient constructs a client for the carbonpanel.v1.MinecraftService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMinecraftServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MinecraftServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	minecraftServiceMethods := v1.File_carbonpanel_v1_minecraft_proto.Services().ByName("MinecraftService").Methods()
	return &minecraftServiceClient{
		getMinecraftVersions: connect.NewClient[v1.GetMinecraftVersionsRequest, v1.GetMinecraftVersionsResponse](
			httpClient,
			baseURL+MinecraftServiceGetMinecraftVersionsProcedure,
			connect.WithSchema(minecraftServiceMethods.ByName("GetMinecraftVersions")),
			connect.WithClientOptions(opts...),
		),
		getModLoaders: connect.NewClient[v1.GetModLoadersRequest, v1.GetModLoadersResponse](
			httpClient,
			baseURL+MinecraftServiceGetModLoadersProcedure,
			connect.WithSchema(minecraftServiceMethods.ByName("GetModLoaders")),
			connect.WithClientOptions(opts...),
		),
		getDockerImages: connect.NewClient[v1.GetDockerImagesRequest, v1.GetDockerImagesResponse](
			httpClient,
			baseURL+MinecraftServiceGetDockerImagesProcedure,
			connect.WithSchema(minecraftServiceMethods.ByName("GetDockerImages")),
			connect.WithClientOptions(opts...),
		),
	}
}

// minecraftServiceClient implements MinecraftServiceClient.
type minecraftServiceClient struct {
	getMinecraftVersions *connect.Client[v1.GetMinecraftVersionsRequest, v1.GetMinecraftVersionsResponse]
	getModLoaders        *connect.Client[v1.GetModLoadersRequest, v1.GetModLoadersResponse]
	getDockerImages      *connect.Client[v1.GetDockerImagesRequest, v1.GetDockerImagesResponse]
}

// GetMinecraftVersions calls carbonpanel.v1.MinecraftService.GetMinecraftVersions.
func (c *minecraftServiceClient) GetMinecraftVersions(ctx context.Context, req *connect.Request[v1.GetMinecraftVersionsRequest]) (*connect.Response[v1.GetMinecraftVersionsResponse], error) {
	return c.getMinecraftVersions.CallUnary(ctx, req)
}

// GetModLoaders calls carbonpanel.v1.MinecraftService.GetModLoaders.
func (c *minecraftServiceClient) GetModLoaders(ctx context.Context, req *connect.Request[v1.GetModLoadersRequest]) (*connect.Response[v1.GetModLoadersResponse], error) {
	return c.getModLoaders.CallUnary(ctx, req)
}

// GetDockerImages calls carbonpanel.v1.MinecraftService.GetDockerImages.
func (c *minecraftServiceClient) GetDockerImages(ctx context.Context, req *connect.Request[v1.GetDockerImagesRequest]) (*connect.Response[v1.GetDockerImagesResponse], error) {
	return c.getDockerImages.CallUnary(ctx, req)
}

// MinecraftServiceHandler is an implementation of the carbonpanel.v1.MinecraftService service.
type MinecraftServiceHandler interface {
	// List all Minecraft versions
	GetMinecraftVersions(context.Context, *connect.Request[v1.GetMinecraftVersionsRequest]) (*connect.Response[v1.GetMinecraftVersionsResponse], error)
	// List supported mod loaders
	GetModLoaders(context.Context, *connect.Request[v1.GetModLoadersRequest]) (*connect.Response[v1.GetModLoadersResponse], error)
	// List available Docker images
	GetDockerImages(context.Context, *connect.Request[v1.GetDockerImagesRequest]) (*connect.Response[v1.GetDockerImagesResponse], error)
}

// NewMinecraftServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMinecraftServiceHandler(svc MinecraftServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	minecraftServiceMethods := v1.File_carbonpanel_v1_minecraft_proto.Services().ByName("MinecraftService").Methods()
	minecraftServiceGetMinecraftVersionsHandler := connect.NewUnaryHandler(
		MinecraftServiceGetMinecraftVersionsProcedure,
		svc.GetMinecraftVersions,
		connect.WithSchema(minecraftServiceMethods.ByName("GetMinecraftVersions")),
		connect.WithHandlerOptions(opts...),
	)
	minecraftServiceGetModLoadersHandler := connect.NewUnaryHandler(
		MinecraftServiceGetModLoadersProcedure,
		svc.GetModLoaders,
		connect.WithSchema(minecraftServiceMethods.ByName("GetModLoaders")),
		connect.WithHandlerOptions(opts...),
	)
	minecraftServiceGetDockerImagesHandler := connect.NewUnaryHandler(
		MinecraftServiceGetDockerImagesProcedure,
		svc.GetDockerImages,
		connect.WithSchema(minecraftServiceMethods.ByName("GetDockerImages")),
		connect.WithHandlerOptions(opts...),
	)
	return "/carbonpanel.v1.MinecraftService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MinecraftServiceGetMinecraftVersionsProcedure:
			minecraftServiceGetMinecraftVersionsHandler.ServeHTTP(w, r)
		case MinecraftServiceGetModLoadersProcedure:
			minecraftServiceGetModLoadersHandler.ServeHTTP(w, r)
		case MinecraftServiceGetDockerImagesProcedure:
			minecraftServiceGetDockerImagesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMinecraftServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMinecraftServiceHandler struct{}

func (UnimplementedMinecraftServiceHandler) GetMinecraftVersions(context.Context, *connect.Request[v1.GetMinecraftVersionsRequest]) (*connect.Response[v1.GetMinecraftVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("carbonpanel.v1.MinecraftService.GetMinecraftVersions is not implemented"))
}

func (UnimplementedMinecraftServiceHandler) GetModLoaders(context.Context, *connect.Request[v1.GetModLoadersRequest]) (*connect.Response[v1.GetModLoadersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("carbonpanel.v1.MinecraftService.GetModLoaders is not implemented"))
}

func (UnimplementedMinecraftServiceHandler) GetDockerImages(context.Context, *connect.Request[v1.GetDockerImagesRequest]) (*connect.Response[v1.GetDockerImagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("carbonpanel.v1.MinecraftService.GetDockerImages is not implemented"))
}
