// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: discopanel/v1/proxy.proto

package discopanelv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/nickheyer/discopanel/pkg/proto/discopanel/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProxyServiceName is the fully-qualified name of the ProxyService service.
	ProxyServiceName = "discopanel.v1.ProxyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProxyServiceGetProxyRoutesProcedure is the fully-qualified name of the ProxyService's
	// GetProxyRoutes RPC.
	ProxyServiceGetProxyRoutesProcedure = "/discopanel.v1.ProxyService/GetProxyRoutes"
	// ProxyServiceGetProxyStatusProcedure is the fully-qualified name of the ProxyService's
	// GetProxyStatus RPC.
	ProxyServiceGetProxyStatusProcedure = "/discopanel.v1.ProxyService/GetProxyStatus"
	// ProxyServiceUpdateProxyConfigProcedure is the fully-qualified name of the ProxyService's
	// UpdateProxyConfig RPC.
	ProxyServiceUpdateProxyConfigProcedure = "/discopanel.v1.ProxyService/UpdateProxyConfig"
	// ProxyServiceGetProxyListenersProcedure is the fully-qualified name of the ProxyService's
	// GetProxyListeners RPC.
	ProxyServiceGetProxyListenersProcedure = "/discopanel.v1.ProxyService/GetProxyListeners"
	// ProxyServiceCreateProxyListenerProcedure is the fully-qualified name of the ProxyService's
	// CreateProxyListener RPC.
	ProxyServiceCreateProxyListenerProcedure = "/discopanel.v1.ProxyService/CreateProxyListener"
	// ProxyServiceUpdateProxyListenerProcedure is the fully-qualified name of the ProxyService's
	// UpdateProxyListener RPC.
	ProxyServiceUpdateProxyListenerProcedure = "/discopanel.v1.ProxyService/UpdateProxyListener"
	// ProxyServiceDeleteProxyListenerProcedure is the fully-qualified name of the ProxyService's
	// DeleteProxyListener RPC.
	ProxyServiceDeleteProxyListenerProcedure = "/discopanel.v1.ProxyService/DeleteProxyListener"
	// ProxyServiceGetServerRoutingProcedure is the fully-qualified name of the ProxyService's
	// GetServerRouting RPC.
	ProxyServiceGetServerRoutingProcedure = "/discopanel.v1.ProxyService/GetServerRouting"
	// ProxyServiceUpdateServerRoutingProcedure is the fully-qualified name of the ProxyService's
	// UpdateServerRouting RPC.
	ProxyServiceUpdateServerRoutingProcedure = "/discopanel.v1.ProxyService/UpdateServerRouting"
)

// ProxyServiceClient is a client for the discopanel.v1.ProxyService service.
type ProxyServiceClient interface {
	// List active proxy routes
	GetProxyRoutes(context.Context, *connect.Request[v1.GetProxyRoutesRequest]) (*connect.Response[v1.GetProxyRoutesResponse], error)
	// Check proxy system status
	GetProxyStatus(context.Context, *connect.Request[v1.GetProxyStatusRequest]) (*connect.Response[v1.GetProxyStatusResponse], error)
	// Modify proxy settings
	UpdateProxyConfig(context.Context, *connect.Request[v1.UpdateProxyConfigRequest]) (*connect.Response[v1.UpdateProxyConfigResponse], error)
	// List all proxy listeners
	GetProxyListeners(context.Context, *connect.Request[v1.GetProxyListenersRequest]) (*connect.Response[v1.GetProxyListenersResponse], error)
	// Add new listener port
	CreateProxyListener(context.Context, *connect.Request[v1.CreateProxyListenerRequest]) (*connect.Response[v1.CreateProxyListenerResponse], error)
	// Modify listener settings
	UpdateProxyListener(context.Context, *connect.Request[v1.UpdateProxyListenerRequest]) (*connect.Response[v1.UpdateProxyListenerResponse], error)
	// Remove listener port
	DeleteProxyListener(context.Context, *connect.Request[v1.DeleteProxyListenerRequest]) (*connect.Response[v1.DeleteProxyListenerResponse], error)
	// Get server proxy configuration
	GetServerRouting(context.Context, *connect.Request[v1.GetServerRoutingRequest]) (*connect.Response[v1.GetServerRoutingResponse], error)
	// Update server proxy hostname
	UpdateServerRouting(context.Context, *connect.Request[v1.UpdateServerRoutingRequest]) (*connect.Response[v1.UpdateServerRoutingResponse], error)
}

// NewProxyServiceClient constructs a client for the discopanel.v1.ProxyService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProxyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProxyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	proxyServiceMethods := v1.File_discopanel_v1_proxy_proto.Services().ByName("ProxyService").Methods()
	return &proxyServiceClient{
		getProxyRoutes: connect.NewClient[v1.GetProxyRoutesRequest, v1.GetProxyRoutesResponse](
			httpClient,
			baseURL+ProxyServiceGetProxyRoutesProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("GetProxyRoutes")),
			connect.WithClientOptions(opts...),
		),
		getProxyStatus: connect.NewClient[v1.GetProxyStatusRequest, v1.GetProxyStatusResponse](
			httpClient,
			baseURL+ProxyServiceGetProxyStatusProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("GetProxyStatus")),
			connect.WithClientOptions(opts...),
		),
		updateProxyConfig: connect.NewClient[v1.UpdateProxyConfigRequest, v1.UpdateProxyConfigResponse](
			httpClient,
			baseURL+ProxyServiceUpdateProxyConfigProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("UpdateProxyConfig")),
			connect.WithClientOptions(opts...),
		),
		getProxyListeners: connect.NewClient[v1.GetProxyListenersRequest, v1.GetProxyListenersResponse](
			httpClient,
			baseURL+ProxyServiceGetProxyListenersProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("GetProxyListeners")),
			connect.WithClientOptions(opts...),
		),
		createProxyListener: connect.NewClient[v1.CreateProxyListenerRequest, v1.CreateProxyListenerResponse](
			httpClient,
			baseURL+ProxyServiceCreateProxyListenerProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("CreateProxyListener")),
			connect.WithClientOptions(opts...),
		),
		updateProxyListener: connect.NewClient[v1.UpdateProxyListenerRequest, v1.UpdateProxyListenerResponse](
			httpClient,
			baseURL+ProxyServiceUpdateProxyListenerProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("UpdateProxyListener")),
			connect.WithClientOptions(opts...),
		),
		deleteProxyListener: connect.NewClient[v1.DeleteProxyListenerRequest, v1.DeleteProxyListenerResponse](
			httpClient,
			baseURL+ProxyServiceDeleteProxyListenerProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("DeleteProxyListener")),
			connect.WithClientOptions(opts...),
		),
		getServerRouting: connect.NewClient[v1.GetServerRoutingRequest, v1.GetServerRoutingResponse](
			httpClient,
			baseURL+ProxyServiceGetServerRoutingProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("GetServerRouting")),
			connect.WithClientOptions(opts...),
		),
		updateServerRouting: connect.NewClient[v1.UpdateServerRoutingRequest, v1.UpdateServerRoutingResponse](
			httpClient,
			baseURL+ProxyServiceUpdateServerRoutingProcedure,
			connect.WithSchema(proxyServiceMethods.ByName("UpdateServerRouting")),
			connect.WithClientOptions(opts...),
		),
	}
}

// proxyServiceClient implements ProxyServiceClient.
type proxyServiceClient struct {
	getProxyRoutes      *connect.Client[v1.GetProxyRoutesRequest, v1.GetProxyRoutesResponse]
	getProxyStatus      *connect.Client[v1.GetProxyStatusRequest, v1.GetProxyStatusResponse]
	updateProxyConfig   *connect.Client[v1.UpdateProxyConfigRequest, v1.UpdateProxyConfigResponse]
	getProxyListeners   *connect.Client[v1.GetProxyListenersRequest, v1.GetProxyListenersResponse]
	createProxyListener *connect.Client[v1.CreateProxyListenerRequest, v1.CreateProxyListenerResponse]
	updateProxyListener *connect.Client[v1.UpdateProxyListenerRequest, v1.UpdateProxyListenerResponse]
	deleteProxyListener *connect.Client[v1.DeleteProxyListenerRequest, v1.DeleteProxyListenerResponse]
	getServerRouting    *connect.Client[v1.GetServerRoutingRequest, v1.GetServerRoutingResponse]
	updateServerRouting *connect.Client[v1.UpdateServerRoutingRequest, v1.UpdateServerRoutingResponse]
}

// GetProxyRoutes calls discopanel.v1.ProxyService.GetProxyRoutes.
func (c *proxyServiceClient) GetProxyRoutes(ctx context.Context, req *connect.Request[v1.GetProxyRoutesRequest]) (*connect.Response[v1.GetProxyRoutesResponse], error) {
	return c.getProxyRoutes.CallUnary(ctx, req)
}

// GetProxyStatus calls discopanel.v1.ProxyService.GetProxyStatus.
func (c *proxyServiceClient) GetProxyStatus(ctx context.Context, req *connect.Request[v1.GetProxyStatusRequest]) (*connect.Response[v1.GetProxyStatusResponse], error) {
	return c.getProxyStatus.CallUnary(ctx, req)
}

// UpdateProxyConfig calls discopanel.v1.ProxyService.UpdateProxyConfig.
func (c *proxyServiceClient) UpdateProxyConfig(ctx context.Context, req *connect.Request[v1.UpdateProxyConfigRequest]) (*connect.Response[v1.UpdateProxyConfigResponse], error) {
	return c.updateProxyConfig.CallUnary(ctx, req)
}

// GetProxyListeners calls discopanel.v1.ProxyService.GetProxyListeners.
func (c *proxyServiceClient) GetProxyListeners(ctx context.Context, req *connect.Request[v1.GetProxyListenersRequest]) (*connect.Response[v1.GetProxyListenersResponse], error) {
	return c.getProxyListeners.CallUnary(ctx, req)
}

// CreateProxyListener calls discopanel.v1.ProxyService.CreateProxyListener.
func (c *proxyServiceClient) CreateProxyListener(ctx context.Context, req *connect.Request[v1.CreateProxyListenerRequest]) (*connect.Response[v1.CreateProxyListenerResponse], error) {
	return c.createProxyListener.CallUnary(ctx, req)
}

// UpdateProxyListener calls discopanel.v1.ProxyService.UpdateProxyListener.
func (c *proxyServiceClient) UpdateProxyListener(ctx context.Context, req *connect.Request[v1.UpdateProxyListenerRequest]) (*connect.Response[v1.UpdateProxyListenerResponse], error) {
	return c.updateProxyListener.CallUnary(ctx, req)
}

// DeleteProxyListener calls discopanel.v1.ProxyService.DeleteProxyListener.
func (c *proxyServiceClient) DeleteProxyListener(ctx context.Context, req *connect.Request[v1.DeleteProxyListenerRequest]) (*connect.Response[v1.DeleteProxyListenerResponse], error) {
	return c.deleteProxyListener.CallUnary(ctx, req)
}

// GetServerRouting calls discopanel.v1.ProxyService.GetServerRouting.
func (c *proxyServiceClient) GetServerRouting(ctx context.Context, req *connect.Request[v1.GetServerRoutingRequest]) (*connect.Response[v1.GetServerRoutingResponse], error) {
	return c.getServerRouting.CallUnary(ctx, req)
}

// UpdateServerRouting calls discopanel.v1.ProxyService.UpdateServerRouting.
func (c *proxyServiceClient) UpdateServerRouting(ctx context.Context, req *connect.Request[v1.UpdateServerRoutingRequest]) (*connect.Response[v1.UpdateServerRoutingResponse], error) {
	return c.updateServerRouting.CallUnary(ctx, req)
}

// ProxyServiceHandler is an implementation of the discopanel.v1.ProxyService service.
type ProxyServiceHandler interface {
	// List active proxy routes
	GetProxyRoutes(context.Context, *connect.Request[v1.GetProxyRoutesRequest]) (*connect.Response[v1.GetProxyRoutesResponse], error)
	// Check proxy system status
	GetProxyStatus(context.Context, *connect.Request[v1.GetProxyStatusRequest]) (*connect.Response[v1.GetProxyStatusResponse], error)
	// Modify proxy settings
	UpdateProxyConfig(context.Context, *connect.Request[v1.UpdateProxyConfigRequest]) (*connect.Response[v1.UpdateProxyConfigResponse], error)
	// List all proxy listeners
	GetProxyListeners(context.Context, *connect.Request[v1.GetProxyListenersRequest]) (*connect.Response[v1.GetProxyListenersResponse], error)
	// Add new listener port
	CreateProxyListener(context.Context, *connect.Request[v1.CreateProxyListenerRequest]) (*connect.Response[v1.CreateProxyListenerResponse], error)
	// Modify listener settings
	UpdateProxyListener(context.Context, *connect.Request[v1.UpdateProxyListenerRequest]) (*connect.Response[v1.UpdateProxyListenerResponse], error)
	// Remove listener port
	DeleteProxyListener(context.Context, *connect.Request[v1.DeleteProxyListenerRequest]) (*connect.Response[v1.DeleteProxyListenerResponse], error)
	// Get server proxy configuration
	GetServerRouting(context.Context, *connect.Request[v1.GetServerRoutingRequest]) (*connect.Response[v1.GetServerRoutingResponse], error)
	// Update server proxy hostname
	UpdateServerRouting(context.Context, *connect.Request[v1.UpdateServerRoutingRequest]) (*connect.Response[v1.UpdateServerRoutingResponse], error)
}

// NewProxyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProxyServiceHandler(svc ProxyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	proxyServiceMethods := v1.File_discopanel_v1_proxy_proto.Services().ByName("ProxyService").Methods()
	proxyServiceGetProxyRoutesHandler := connect.NewUnaryHandler(
		ProxyServiceGetProxyRoutesProcedure,
		svc.GetProxyRoutes,
		connect.WithSchema(proxyServiceMethods.ByName("GetProxyRoutes")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceGetProxyStatusHandler := connect.NewUnaryHandler(
		ProxyServiceGetProxyStatusProcedure,
		svc.GetProxyStatus,
		connect.WithSchema(proxyServiceMethods.ByName("GetProxyStatus")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceUpdateProxyConfigHandler := connect.NewUnaryHandler(
		ProxyServiceUpdateProxyConfigProcedure,
		svc.UpdateProxyConfig,
		connect.WithSchema(proxyServiceMethods.ByName("UpdateProxyConfig")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceGetProxyListenersHandler := connect.NewUnaryHandler(
		ProxyServiceGetProxyListenersProcedure,
		svc.GetProxyListeners,
		connect.WithSchema(proxyServiceMethods.ByName("GetProxyListeners")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceCreateProxyListenerHandler := connect.NewUnaryHandler(
		ProxyServiceCreateProxyListenerProcedure,
		svc.CreateProxyListener,
		connect.WithSchema(proxyServiceMethods.ByName("CreateProxyListener")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceUpdateProxyListenerHandler := connect.NewUnaryHandler(
		ProxyServiceUpdateProxyListenerProcedure,
		svc.UpdateProxyListener,
		connect.WithSchema(proxyServiceMethods.ByName("UpdateProxyListener")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceDeleteProxyListenerHandler := connect.NewUnaryHandler(
		ProxyServiceDeleteProxyListenerProcedure,
		svc.DeleteProxyListener,
		connect.WithSchema(proxyServiceMethods.ByName("DeleteProxyListener")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceGetServerRoutingHandler := connect.NewUnaryHandler(
		ProxyServiceGetServerRoutingProcedure,
		svc.GetServerRouting,
		connect.WithSchema(proxyServiceMethods.ByName("GetServerRouting")),
		connect.WithHandlerOptions(opts...),
	)
	proxyServiceUpdateServerRoutingHandler := connect.NewUnaryHandler(
		ProxyServiceUpdateServerRoutingProcedure,
		svc.UpdateServerRouting,
		connect.WithSchema(proxyServiceMethods.ByName("UpdateServerRouting")),
		connect.WithHandlerOptions(opts...),
	)
	return "/discopanel.v1.ProxyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProxyServiceGetProxyRoutesProcedure:
			proxyServiceGetProxyRoutesHandler.ServeHTTP(w, r)
		case ProxyServiceGetProxyStatusProcedure:
			proxyServiceGetProxyStatusHandler.ServeHTTP(w, r)
		case ProxyServiceUpdateProxyConfigProcedure:
			proxyServiceUpdateProxyConfigHandler.ServeHTTP(w, r)
		case ProxyServiceGetProxyListenersProcedure:
			proxyServiceGetProxyListenersHandler.ServeHTTP(w, r)
		case ProxyServiceCreateProxyListenerProcedure:
			proxyServiceCreateProxyListenerHandler.ServeHTTP(w, r)
		case ProxyServiceUpdateProxyListenerProcedure:
			proxyServiceUpdateProxyListenerHandler.ServeHTTP(w, r)
		case ProxyServiceDeleteProxyListenerProcedure:
			proxyServiceDeleteProxyListenerHandler.ServeHTTP(w, r)
		case ProxyServiceGetServerRoutingProcedure:
			proxyServiceGetServerRoutingHandler.ServeHTTP(w, r)
		case ProxyServiceUpdateServerRoutingProcedure:
			proxyServiceUpdateServerRoutingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProxyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProxyServiceHandler struct{}

func (UnimplementedProxyServiceHandler) GetProxyRoutes(context.Context, *connect.Request[v1.GetProxyRoutesRequest]) (*connect.Response[v1.GetProxyRoutesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.GetProxyRoutes is not implemented"))
}

func (UnimplementedProxyServiceHandler) GetProxyStatus(context.Context, *connect.Request[v1.GetProxyStatusRequest]) (*connect.Response[v1.GetProxyStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.GetProxyStatus is not implemented"))
}

func (UnimplementedProxyServiceHandler) UpdateProxyConfig(context.Context, *connect.Request[v1.UpdateProxyConfigRequest]) (*connect.Response[v1.UpdateProxyConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.UpdateProxyConfig is not implemented"))
}

func (UnimplementedProxyServiceHandler) GetProxyListeners(context.Context, *connect.Request[v1.GetProxyListenersRequest]) (*connect.Response[v1.GetProxyListenersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.GetProxyListeners is not implemented"))
}

func (UnimplementedProxyServiceHandler) CreateProxyListener(context.Context, *connect.Request[v1.CreateProxyListenerRequest]) (*connect.Response[v1.CreateProxyListenerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.CreateProxyListener is not implemented"))
}

func (UnimplementedProxyServiceHandler) UpdateProxyListener(context.Context, *connect.Request[v1.UpdateProxyListenerRequest]) (*connect.Response[v1.UpdateProxyListenerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.UpdateProxyListener is not implemented"))
}

func (UnimplementedProxyServiceHandler) DeleteProxyListener(context.Context, *connect.Request[v1.DeleteProxyListenerRequest]) (*connect.Response[v1.DeleteProxyListenerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.DeleteProxyListener is not implemented"))
}

func (UnimplementedProxyServiceHandler) GetServerRouting(context.Context, *connect.Request[v1.GetServerRoutingRequest]) (*connect.Response[v1.GetServerRoutingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.GetServerRouting is not implemented"))
}

func (UnimplementedProxyServiceHandler) UpdateServerRouting(context.Context, *connect.Request[v1.UpdateServerRoutingRequest]) (*connect.Response[v1.UpdateServerRoutingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("discopanel.v1.ProxyService.UpdateServerRouting is not implemented"))
}
