// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cloud/v1/auth.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSessionRequest is the session introspection request.
type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_cloud_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{0}
}

// GetSessionResponse carries the resolved principal.
type GetSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved principal for the request (includes the active org).
	Principal *Principal `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// Orgs the caller may switch to.
	Orgs []*Org `protobuf:"bytes,2,rep,name=orgs,proto3" json:"orgs,omitempty"`
	// True when the caller authenticated with an API key rather than a session.
	ViaApiKey     bool `protobuf:"varint,3,opt,name=via_api_key,json=viaApiKey,proto3" json:"via_api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_cloud_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *GetSessionResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *GetSessionResponse) GetOrgs() []*Org {
	if x != nil {
		return x.Orgs
	}
	return nil
}

func (x *GetSessionResponse) GetViaApiKey() bool {
	if x != nil {
		return x.ViaApiKey
	}
	return false
}

// ListMyOrgsRequest is the org listing request.
type ListMyOrgsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional pagination.
	Page          *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrgsRequest) Reset() {
	*x = ListMyOrgsRequest{}
	mi := &file_cloud_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrgsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrgsRequest) ProtoMessage() {}

func (x *ListMyOrgsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrgsRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrgsRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ListMyOrgsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// ListMyOrgsResponse lists the caller's orgs.
type ListMyOrgsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Orgs the caller belongs to.
	Orgs []*Org `protobuf:"bytes,1,rep,name=orgs,proto3" json:"orgs,omitempty"`
	// Pagination cursor.
	Page          *PageResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrgsResponse) Reset() {
	*x = ListMyOrgsResponse{}
	mi := &file_cloud_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrgsResponse) ProtoMessage() {}

func (x *ListMyOrgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrgsResponse.ProtoReflect.Descriptor instead.
func (*ListMyOrgsResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ListMyOrgsResponse) GetOrgs() []*Org {
	if x != nil {
		return x.Orgs
	}
	return nil
}

func (x *ListMyOrgsResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ListMyPermissionsRequest is the permission listing request.
type ListMyPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyPermissionsRequest) Reset() {
	*x = ListMyPermissionsRequest{}
	mi := &file_cloud_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyPermissionsRequest) ProtoMessage() {}

func (x *ListMyPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListMyPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{4}
}

// ListMyPermissionsResponse lists effective permissions.
type ListMyPermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Permission strings of the form "resource.action" that the caller holds.
	Permissions []string `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Role the permissions were derived from.
	Role          Role `protobuf:"varint,2,opt,name=role,proto3,enum=cloud.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyPermissionsResponse) Reset() {
	*x = ListMyPermissionsResponse{}
	mi := &file_cloud_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyPermissionsResponse) ProtoMessage() {}

func (x *ListMyPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListMyPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyPermissionsResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ListMyPermissionsResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

// ApiKey is a long-lived credential for programmatic access, scoped to one org.
type ApiKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side identifier; never the secret itself.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning org id.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Human label chosen at creation.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// First characters of the key, safe to display for identification.
	Prefix string `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// Permission strings granted to the key.
	Permissions []string `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Last time the key authenticated a request.
	LastUsedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	// Key expiry; absent means no expiry.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Revocation time; absent means active.
	RevokedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// Creation time.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	mi := &file_cloud_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ApiKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiKey) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ApiKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ApiKey) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ApiKey) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ApiKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *ApiKey) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ApiKey) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *ApiKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListApiKeysRequest is the key listing request.
type ListApiKeysRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional pagination.
	Page          *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysRequest) Reset() {
	*x = ListApiKeysRequest{}
	mi := &file_cloud_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRequest) ProtoMessage() {}

func (x *ListApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysRequest.ProtoReflect.Descriptor instead.
func (*ListApiKeysRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ListApiKeysRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// ListApiKeysResponse lists keys without secrets.
type ListApiKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keys in the active org.
	ApiKeys []*ApiKey `protobuf:"bytes,1,rep,name=api_keys,json=apiKeys,proto3" json:"api_keys,omitempty"`
	// Pagination cursor.
	Page          *PageResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApiKeysResponse) Reset() {
	*x = ListApiKeysResponse{}
	mi := &file_cloud_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysResponse) ProtoMessage() {}

func (x *ListApiKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApiKeysResponse.ProtoReflect.Descriptor instead.
func (*ListApiKeysResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ListApiKeysResponse) GetApiKeys() []*ApiKey {
	if x != nil {
		return x.ApiKeys
	}
	return nil
}

func (x *ListApiKeysResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// CreateApiKeyRequest describes the key to mint.
type CreateApiKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human label for the key.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Permission strings to grant; must be a subset of the caller's permissions.
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Optional expiry as a duration in seconds from now; zero means no expiry.
	ExpiresInSeconds int64 `protobuf:"varint,3,opt,name=expires_in_seconds,json=expiresInSeconds,proto3" json:"expires_in_seconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_cloud_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *CreateApiKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateApiKeyRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateApiKeyRequest) GetExpiresInSeconds() int64 {
	if x != nil {
		return x.ExpiresInSeconds
	}
	return 0
}

// CreateApiKeyResponse returns the plaintext key once.
type CreateApiKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key metadata.
	ApiKey *ApiKey `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// Plaintext secret; the only time it is ever returned.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyResponse) Reset() {
	*x = CreateApiKeyResponse{}
	mi := &file_cloud_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyResponse) ProtoMessage() {}

func (x *CreateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *CreateApiKeyResponse) GetApiKey() *ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *CreateApiKeyResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

// RevokeApiKeyRequest identifies the key to revoke.
type RevokeApiKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyRequest) Reset() {
	*x = RevokeApiKeyRequest{}
	mi := &file_cloud_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyRequest) ProtoMessage() {}

func (x *RevokeApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeApiKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RevokeApiKeyResponse acknowledges revocation.
type RevokeApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyResponse) Reset() {
	*x = RevokeApiKeyResponse{}
	mi := &file_cloud_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyResponse) ProtoMessage() {}

func (x *RevokeApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{12}
}

// RotateApiKeyRequest identifies the key to rotate.
type RotateApiKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateApiKeyRequest) Reset() {
	*x = RotateApiKeyRequest{}
	mi := &file_cloud_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateApiKeyRequest) ProtoMessage() {}

func (x *RotateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *RotateApiKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RotateApiKeyResponse returns the replacement key.
type RotateApiKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New key metadata.
	ApiKey *ApiKey `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// New plaintext secret, returned once.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateApiKeyResponse) Reset() {
	*x = RotateApiKeyResponse{}
	mi := &file_cloud_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateApiKeyResponse) ProtoMessage() {}

func (x *RotateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *RotateApiKeyResponse) GetApiKey() *ApiKey {
	if x != nil {
		return x.ApiKey
	}
	return nil
}

func (x *RotateApiKeyResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_cloud_v1_auth_proto protoreflect.FileDescriptor

const file_cloud_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x13cloud/v1/auth.proto\x12\bcloud.v1\x1a\x15cloud/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11GetSessionRequest\"\x8a\x01\n" +
	"\x12GetSessionResponse\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.cloud.v1.PrincipalR\tprincipal\x12!\n" +
	"\x04orgs\x18\x02 \x03(\v2\r.cloud.v1.OrgR\x04orgs\x12\x1e\n" +
	"\vvia_api_key\x18\x03 \x01(\bR\tviaApiKey\">\n" +
	"\x11ListMyOrgsRequest\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.cloud.v1.PageRequestR\x04page\"c\n" +
	"\x12ListMyOrgsResponse\x12!\n" +
	"\x04orgs\x18\x01 \x03(\v2\r.cloud.v1.OrgR\x04orgs\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cloud.v1.PageResponseR\x04page\"\x1a\n" +
	"\x18ListMyPermissionsRequest\"a\n" +
	"\x19ListMyPermissionsResponse\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions\x12\"\n" +
	"\x04role\x18\x02 \x01(\x0e2\x0e.cloud.v1.RoleR\x04role\"\xec\x02\n" +
	"\x06ApiKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"revoked_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"?\n" +
	"\x12ListApiKeysRequest\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.cloud.v1.PageRequestR\x04page\"n\n" +
	"\x13ListApiKeysResponse\x12+\n" +
	"\bapi_keys\x18\x01 \x03(\v2\x10.cloud.v1.ApiKeyR\aapiKeys\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cloud.v1.PageResponseR\x04page\"y\n" +
	"\x13CreateApiKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12,\n" +
	"\x12expires_in_seconds\x18\x03 \x01(\x03R\x10expiresInSeconds\"Y\n" +
	"\x14CreateApiKeyResponse\x12)\n" +
	"\aapi_key\x18\x01 \x01(\v2\x10.cloud.v1.ApiKeyR\x06apiKey\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"%\n" +
	"\x13RevokeApiKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14RevokeApiKeyResponse\"%\n" +
	"\x13RotateApiKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x14RotateApiKeyResponse\x12)\n" +
	"\aapi_key\x18\x01 \x01(\v2\x10.cloud.v1.ApiKeyR\x06apiKey\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret2\x80\x02\n" +
	"\x0eSessionService\x12G\n" +
	"\n" +
	"GetSession\x12\x1b.cloud.v1.GetSessionRequest\x1a\x1c.cloud.v1.GetSessionResponse\x12G\n" +
	"\n" +
	"ListMyOrgs\x12\x1b.cloud.v1.ListMyOrgsRequest\x1a\x1c.cloud.v1.ListMyOrgsResponse\x12\\\n" +
	"\x11ListMyPermissions\x12\".cloud.v1.ListMyPermissionsRequest\x1a#.cloud.v1.ListMyPermissionsResponse2\xc8\x02\n" +
	"\rApiKeyService\x12J\n" +
	"\vListApiKeys\x12\x1c.cloud.v1.ListApiKeysRequest\x1a\x1d.cloud.v1.ListApiKeysResponse\x12M\n" +
	"\fCreateApiKey\x12\x1d.cloud.v1.CreateApiKeyRequest\x1a\x1e.cloud.v1.CreateApiKeyResponse\x12M\n" +
	"\fRevokeApiKey\x12\x1d.cloud.v1.RevokeApiKeyRequest\x1a\x1e.cloud.v1.RevokeApiKeyResponse\x12M\n" +
	"\fRotateApiKey\x12\x1d.cloud.v1.RotateApiKeyRequest\x1a\x1e.cloud.v1.RotateApiKeyResponseB<Z:github.com/athNdev/carbon-panel/pkg/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_auth_proto_rawDescOnce sync.Once
	file_cloud_v1_auth_proto_rawDescData []byte
)

func file_cloud_v1_auth_proto_rawDescGZIP() []byte {
	file_cloud_v1_auth_proto_rawDescOnce.Do(func() {
		file_cloud_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_auth_proto_rawDesc), len(file_cloud_v1_auth_proto_rawDesc)))
	})
	return file_cloud_v1_auth_proto_rawDescData
}

var file_cloud_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cloud_v1_auth_proto_goTypes = []any{
	(*GetSessionRequest)(nil),         // 0: cloud.v1.GetSessionRequest
	(*GetSessionResponse)(nil),        // 1: cloud.v1.GetSessionResponse
	(*ListMyOrgsRequest)(nil),         // 2: cloud.v1.ListMyOrgsRequest
	(*ListMyOrgsResponse)(nil),        // 3: cloud.v1.ListMyOrgsResponse
	(*ListMyPermissionsRequest)(nil),  // 4: cloud.v1.ListMyPermissionsRequest
	(*ListMyPermissionsResponse)(nil), // 5: cloud.v1.ListMyPermissionsResponse
	(*ApiKey)(nil),                    // 6: cloud.v1.ApiKey
	(*ListApiKeysRequest)(nil),        // 7: cloud.v1.ListApiKeysRequest
	(*ListApiKeysResponse)(nil),       // 8: cloud.v1.ListApiKeysResponse
	(*CreateApiKeyRequest)(nil),       // 9: cloud.v1.CreateApiKeyRequest
	(*CreateApiKeyResponse)(nil),      // 10: cloud.v1.CreateApiKeyResponse
	(*RevokeApiKeyRequest)(nil),       // 11: cloud.v1.RevokeApiKeyRequest
	(*RevokeApiKeyResponse)(nil),      // 12: cloud.v1.RevokeApiKeyResponse
	(*RotateApiKeyRequest)(nil),       // 13: cloud.v1.RotateApiKeyRequest
	(*RotateApiKeyResponse)(nil),      // 14: cloud.v1.RotateApiKeyResponse
	(*Principal)(nil),                 // 15: cloud.v1.Principal
	(*Org)(nil),                       // 16: cloud.v1.Org
	(*PageRequest)(nil),               // 17: cloud.v1.PageRequest
	(*PageResponse)(nil),              // 18: cloud.v1.PageResponse
	(Role)(0),                         // 19: cloud.v1.Role
	(*timestamppb.Timestamp)(nil),     // 20: google.protobuf.Timestamp
}
var file_cloud_v1_auth_proto_depIdxs = []int32{
	15, // 0: cloud.v1.GetSessionResponse.principal:type_name -> cloud.v1.Principal
	16, // 1: cloud.v1.GetSessionResponse.orgs:type_name -> cloud.v1.Org
	17, // 2: cloud.v1.ListMyOrgsRequest.page:type_name -> cloud.v1.PageRequest
	16, // 3: cloud.v1.ListMyOrgsResponse.orgs:type_name -> cloud.v1.Org
	18, // 4: cloud.v1.ListMyOrgsResponse.page:type_name -> cloud.v1.PageResponse
	19, // 5: cloud.v1.ListMyPermissionsResponse.role:type_name -> cloud.v1.Role
	20, // 6: cloud.v1.ApiKey.last_used_at:type_name -> google.protobuf.Timestamp
	20, // 7: cloud.v1.ApiKey.expires_at:type_name -> google.protobuf.Timestamp
	20, // 8: cloud.v1.ApiKey.revoked_at:type_name -> google.protobuf.Timestamp
	20, // 9: cloud.v1.ApiKey.created_at:type_name -> google.protobuf.Timestamp
	17, // 10: cloud.v1.ListApiKeysRequest.page:type_name -> cloud.v1.PageRequest
	6,  // 11: cloud.v1.ListApiKeysResponse.api_keys:type_name -> cloud.v1.ApiKey
	18, // 12: cloud.v1.ListApiKeysResponse.page:type_name -> cloud.v1.PageResponse
	6,  // 13: cloud.v1.CreateApiKeyResponse.api_key:type_name -> cloud.v1.ApiKey
	6,  // 14: cloud.v1.RotateApiKeyResponse.api_key:type_name -> cloud.v1.ApiKey
	0,  // 15: cloud.v1.SessionService.GetSession:input_type -> cloud.v1.GetSessionRequest
	2,  // 16: cloud.v1.SessionService.ListMyOrgs:input_type -> cloud.v1.ListMyOrgsRequest
	4,  // 17: cloud.v1.SessionService.ListMyPermissions:input_type -> cloud.v1.ListMyPermissionsRequest
	7,  // 18: cloud.v1.ApiKeyService.ListApiKeys:input_type -> cloud.v1.ListApiKeysRequest
	9,  // 19: cloud.v1.ApiKeyService.CreateApiKey:input_type -> cloud.v1.CreateApiKeyRequest
	11, // 20: cloud.v1.ApiKeyService.RevokeApiKey:input_type -> cloud.v1.RevokeApiKeyRequest
	13, // 21: cloud.v1.ApiKeyService.RotateApiKey:input_type -> cloud.v1.RotateApiKeyRequest
	1,  // 22: cloud.v1.SessionService.GetSession:output_type -> cloud.v1.GetSessionResponse
	3,  // 23: cloud.v1.SessionService.ListMyOrgs:output_type -> cloud.v1.ListMyOrgsResponse
	5,  // 24: cloud.v1.SessionService.ListMyPermissions:output_type -> cloud.v1.ListMyPermissionsResponse
	8,  // 25: cloud.v1.ApiKeyService.ListApiKeys:output_type -> cloud.v1.ListApiKeysResponse
	10, // 26: cloud.v1.ApiKeyService.CreateApiKey:output_type -> cloud.v1.CreateApiKeyResponse
	12, // 27: cloud.v1.ApiKeyService.RevokeApiKey:output_type -> cloud.v1.RevokeApiKeyResponse
	14, // 28: cloud.v1.ApiKeyService.RotateApiKey:output_type -> cloud.v1.RotateApiKeyResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cloud_v1_auth_proto_init() }
func file_cloud_v1_auth_proto_init() {
	if File_cloud_v1_auth_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_auth_proto_rawDesc), len(file_cloud_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cloud_v1_auth_proto_goTypes,
		DependencyIndexes: file_cloud_v1_auth_proto_depIdxs,
		MessageInfos:      file_cloud_v1_auth_proto_msgTypes,
	}.Build()
	File_cloud_v1_auth_proto = out.File
	file_cloud_v1_auth_proto_goTypes = nil
	file_cloud_v1_auth_proto_depIdxs = nil
}
