// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cloud/v1/node.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeCapacity is the resource envelope a node offers to workloads.
type NodeCapacity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Guaranteed virtual CPUs.
	Vcpu int32 `protobuf:"varint,1,opt,name=vcpu,proto3" json:"vcpu,omitempty"`
	// Total RAM in MiB.
	RamMb int64 `protobuf:"varint,2,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	// Total disk in GiB.
	DiskGb int32 `protobuf:"varint,3,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	// Maximum number of concurrent workloads; zero means unbounded.
	MaxWorkloads  int32 `protobuf:"varint,4,opt,name=max_workloads,json=maxWorkloads,proto3" json:"max_workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCapacity) Reset() {
	*x = NodeCapacity{}
	mi := &file_cloud_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapacity) ProtoMessage() {}

func (x *NodeCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapacity.ProtoReflect.Descriptor instead.
func (*NodeCapacity) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeCapacity) GetVcpu() int32 {
	if x != nil {
		return x.Vcpu
	}
	return 0
}

func (x *NodeCapacity) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *NodeCapacity) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *NodeCapacity) GetMaxWorkloads() int32 {
	if x != nil {
		return x.MaxWorkloads
	}
	return 0
}

// NodeAllocation is what is currently committed on a node.
type NodeAllocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sum of workload CPU reservations, millicores.
	CpuMillicores int64 `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	// Sum of workload memory reservations in MiB.
	RamMb int64 `protobuf:"varint,2,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`
	// Sum of workload disk reservations in GiB.
	DiskGb int32 `protobuf:"varint,3,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	// Number of workloads currently placed on the node.
	WorkloadCount int32 `protobuf:"varint,4,opt,name=workload_count,json=workloadCount,proto3" json:"workload_count,omitempty"`
	// Number of those workloads reporting RUNNING.
	RunningCount  int32 `protobuf:"varint,5,opt,name=running_count,json=runningCount,proto3" json:"running_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAllocation) Reset() {
	*x = NodeAllocation{}
	mi := &file_cloud_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAllocation) ProtoMessage() {}

func (x *NodeAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAllocation.ProtoReflect.Descriptor instead.
func (*NodeAllocation) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeAllocation) GetCpuMillicores() int64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *NodeAllocation) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *NodeAllocation) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *NodeAllocation) GetWorkloadCount() int32 {
	if x != nil {
		return x.WorkloadCount
	}
	return 0
}

func (x *NodeAllocation) GetRunningCount() int32 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

// NodeMetrics is the latest resource telemetry reported by the agent.
type NodeMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU utilisation as a percentage of the node's cores.
	CpuPercent float64 `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	// Used RAM in MiB.
	MemUsedMb int64 `protobuf:"varint,2,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	// Used disk in GiB.
	DiskUsedGb int32 `protobuf:"varint,3,opt,name=disk_used_gb,json=diskUsedGb,proto3" json:"disk_used_gb,omitempty"`
	// Reported Docker Engine version.
	DockerVersion string `protobuf:"bytes,4,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	// Node agent version.
	AgentVersion string `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// 1-minute load average.
	Load1         float64 `protobuf:"fixed64,7,opt,name=load1,proto3" json:"load1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_cloud_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeMetrics) GetMemUsedMb() int64 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *NodeMetrics) GetDiskUsedGb() int32 {
	if x != nil {
		return x.DiskUsedGb
	}
	return 0
}

func (x *NodeMetrics) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *NodeMetrics) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *NodeMetrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

// Node is a machine that can run workloads for an org, whether the tenant
// brought it or Carbon Cloud provisioned it.
type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side node id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning org id.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Display name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// How the node joined.
	Origin NodeOrigin `protobuf:"varint,4,opt,name=origin,proto3,enum=cloud.v1.NodeOrigin" json:"origin,omitempty"`
	// Cloud provider for managed nodes.
	Provider ProviderId `protobuf:"varint,5,opt,name=provider,proto3,enum=cloud.v1.ProviderId" json:"provider,omitempty"`
	// Node type the node satisfies.
	NodeTypeId string `protobuf:"bytes,6,opt,name=node_type_id,json=nodeTypeId,proto3" json:"node_type_id,omitempty"`
	// Cloud region, for managed nodes.
	Region string `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	// Current liveness.
	Status NodeStatus `protobuf:"varint,8,opt,name=status,proto3,enum=cloud.v1.NodeStatus" json:"status,omitempty"`
	// Hostname reported by the agent.
	Hostname string `protobuf:"bytes,9,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Public address, when known.
	PublicIp string `protobuf:"bytes,10,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	// Private address, when known.
	PrivateIp string `protobuf:"bytes,11,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	// Declared capacity.
	Capacity *NodeCapacity `protobuf:"bytes,12,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Current allocation.
	Allocation *NodeAllocation `protobuf:"bytes,13,opt,name=allocation,proto3" json:"allocation,omitempty"`
	// Latest telemetry, absent until the first heartbeat.
	Metrics *NodeMetrics `protobuf:"bytes,14,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// Operator-supplied labels used for placement.
	Labels map[string]string `protobuf:"bytes,15,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// SHA-256 fingerprint of the agent's client certificate.
	AgentFingerprint string `protobuf:"bytes,16,opt,name=agent_fingerprint,json=agentFingerprint,proto3" json:"agent_fingerprint,omitempty"`
	// Provisioning run that produced the node, for managed nodes.
	ProvisionId string `protobuf:"bytes,17,opt,name=provision_id,json=provisionId,proto3" json:"provision_id,omitempty"`
	// Last heartbeat time.
	LastHeartbeat *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	// Creation time.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Last modification time.
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// True when the node is reserved for system workloads and cannot be deleted.
	IsSystem      bool `protobuf:"varint,21,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_cloud_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetOrigin() NodeOrigin {
	if x != nil {
		return x.Origin
	}
	return NodeOrigin_NODE_ORIGIN_UNSPECIFIED
}

func (x *Node) GetProvider() ProviderId {
	if x != nil {
		return x.Provider
	}
	return ProviderId_PROVIDER_ID_UNSPECIFIED
}

func (x *Node) GetNodeTypeId() string {
	if x != nil {
		return x.NodeTypeId
	}
	return ""
}

func (x *Node) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Node) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *Node) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Node) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *Node) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *Node) GetCapacity() *NodeCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *Node) GetAllocation() *NodeAllocation {
	if x != nil {
		return x.Allocation
	}
	return nil
}

func (x *Node) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetAgentFingerprint() string {
	if x != nil {
		return x.AgentFingerprint
	}
	return ""
}

func (x *Node) GetProvisionId() string {
	if x != nil {
		return x.ProvisionId
	}
	return ""
}

func (x *Node) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *Node) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Node) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Node) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

// JoinToken authorises exactly one node registration.
type JoinToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token id (the secret is derived from this plus a nonce).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Owning org id.
	OrgId string `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Human label, e.g. "homeserver-1".
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Node type the joining node is expected to satisfy.
	NodeTypeId string `protobuf:"bytes,4,opt,name=node_type_id,json=nodeTypeId,proto3" json:"node_type_id,omitempty"`
	// Origin the node will be recorded with.
	Origin NodeOrigin `protobuf:"varint,5,opt,name=origin,proto3,enum=cloud.v1.NodeOrigin" json:"origin,omitempty"`
	// Provisioning run the token belongs to, for managed nodes.
	ProvisionId string `protobuf:"bytes,6,opt,name=provision_id,json=provisionId,proto3" json:"provision_id,omitempty"`
	// Expiry time.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Redemption time; a redeemed token cannot be redeemed again.
	UsedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`
	// Node that consumed the token.
	UsedByNodeId string `protobuf:"bytes,9,opt,name=used_by_node_id,json=usedByNodeId,proto3" json:"used_by_node_id,omitempty"`
	// Revocation time.
	RevokedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	// Creation time.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinToken) Reset() {
	*x = JoinToken{}
	mi := &file_cloud_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinToken) ProtoMessage() {}

func (x *JoinToken) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinToken.ProtoReflect.Descriptor instead.
func (*JoinToken) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *JoinToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinToken) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *JoinToken) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinToken) GetNodeTypeId() string {
	if x != nil {
		return x.NodeTypeId
	}
	return ""
}

func (x *JoinToken) GetOrigin() NodeOrigin {
	if x != nil {
		return x.Origin
	}
	return NodeOrigin_NODE_ORIGIN_UNSPECIFIED
}

func (x *JoinToken) GetProvisionId() string {
	if x != nil {
		return x.ProvisionId
	}
	return ""
}

func (x *JoinToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *JoinToken) GetUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UsedAt
	}
	return nil
}

func (x *JoinToken) GetUsedByNodeId() string {
	if x != nil {
		return x.UsedByNodeId
	}
	return ""
}

func (x *JoinToken) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *JoinToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListNodesRequest lists nodes.
type ListNodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional status filter.
	Status NodeStatus `protobuf:"varint,1,opt,name=status,proto3,enum=cloud.v1.NodeStatus" json:"status,omitempty"`
	// Optional origin filter.
	Origin NodeOrigin `protobuf:"varint,2,opt,name=origin,proto3,enum=cloud.v1.NodeOrigin" json:"origin,omitempty"`
	// Optional pagination.
	Page          *PageRequest `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *ListNodesRequest) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *ListNodesRequest) GetOrigin() NodeOrigin {
	if x != nil {
		return x.Origin
	}
	return NodeOrigin_NODE_ORIGIN_UNSPECIFIED
}

func (x *ListNodesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// ListNodesResponse lists nodes.
type ListNodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nodes in the active org.
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Pagination cursor.
	Page          *PageResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// GetNodeRequest fetches one node.
type GetNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetNodeResponse returns one node.
type GetNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested node.
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// UpdateNodeRequest patches a node.
type UpdateNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New display name; unchanged when omitted.
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Replaces the label set when present.
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// New declared capacity; unchanged when omitted. Shrinking below current
	// allocation is rejected.
	Capacity      *NodeCapacity `protobuf:"bytes,3,opt,name=capacity,proto3,oneof" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeRequest) Reset() {
	*x = UpdateNodeRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeRequest) ProtoMessage() {}

func (x *UpdateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNodeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateNodeRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateNodeRequest) GetCapacity() *NodeCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

// UpdateNodeResponse returns the updated node.
type UpdateNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated node.
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeResponse) Reset() {
	*x = UpdateNodeResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeResponse) ProtoMessage() {}

func (x *UpdateNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// DrainNodeRequest drains a node.
type DrainNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{11}
}

func (x *DrainNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DrainNodeResponse returns the updated node.
type DrainNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The drained node.
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *DrainNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// ResumeNodeRequest resumes a drained node.
type ResumeNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeNodeRequest) Reset() {
	*x = ResumeNodeRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeNodeRequest) ProtoMessage() {}

func (x *ResumeNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeNodeRequest.ProtoReflect.Descriptor instead.
func (*ResumeNodeRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *ResumeNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ResumeNodeResponse returns the updated node.
type ResumeNodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resumed node.
	Node          *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeNodeResponse) Reset() {
	*x = ResumeNodeResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeNodeResponse) ProtoMessage() {}

func (x *ResumeNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeNodeResponse.ProtoReflect.Descriptor instead.
func (*ResumeNodeResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *ResumeNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// DeleteNodeRequest deletes a node.
type DeleteNodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When true, running workloads are stopped first.
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteNodeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// DeleteNodeResponse acknowledges deletion.
type DeleteNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeResponse) Reset() {
	*x = DeleteNodeResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeResponse) ProtoMessage() {}

func (x *DeleteNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteNodeResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{16}
}

// CreateJoinTokenRequest mints a join token.
type CreateJoinTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human label, usually the machine's name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Node type the node will be recorded under.
	NodeTypeId string `protobuf:"bytes,2,opt,name=node_type_id,json=nodeTypeId,proto3" json:"node_type_id,omitempty"`
	// Validity window in seconds; the server clamps it.
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenRequest) Reset() {
	*x = CreateJoinTokenRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenRequest) ProtoMessage() {}

func (x *CreateJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{17}
}

func (x *CreateJoinTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateJoinTokenRequest) GetNodeTypeId() string {
	if x != nil {
		return x.NodeTypeId
	}
	return ""
}

func (x *CreateJoinTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// CreateJoinTokenResponse returns the token and the exact join command to run.
type CreateJoinTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token metadata.
	Token *JoinToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Plaintext token secret; returned once.
	Secret string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	// Ready-to-paste join command for the target host.
	JoinCommand   string `protobuf:"bytes,3,opt,name=join_command,json=joinCommand,proto3" json:"join_command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJoinTokenResponse) Reset() {
	*x = CreateJoinTokenResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJoinTokenResponse) ProtoMessage() {}

func (x *CreateJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *CreateJoinTokenResponse) GetToken() *JoinToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CreateJoinTokenResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateJoinTokenResponse) GetJoinCommand() string {
	if x != nil {
		return x.JoinCommand
	}
	return ""
}

// ListJoinTokensRequest lists tokens.
type ListJoinTokensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional pagination.
	Page          *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJoinTokensRequest) Reset() {
	*x = ListJoinTokensRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJoinTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJoinTokensRequest) ProtoMessage() {}

func (x *ListJoinTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJoinTokensRequest.ProtoReflect.Descriptor instead.
func (*ListJoinTokensRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *ListJoinTokensRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// ListJoinTokensResponse lists tokens.
type ListJoinTokensResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tokens in the active org.
	Tokens []*JoinToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// Pagination cursor.
	Page          *PageResponse `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJoinTokensResponse) Reset() {
	*x = ListJoinTokensResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJoinTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJoinTokensResponse) ProtoMessage() {}

func (x *ListJoinTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJoinTokensResponse.ProtoReflect.Descriptor instead.
func (*ListJoinTokensResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{20}
}

func (x *ListJoinTokensResponse) GetTokens() []*JoinToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListJoinTokensResponse) GetPage() *PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// RevokeJoinTokenRequest revokes a token.
type RevokeJoinTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeJoinTokenRequest) Reset() {
	*x = RevokeJoinTokenRequest{}
	mi := &file_cloud_v1_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeJoinTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeJoinTokenRequest) ProtoMessage() {}

func (x *RevokeJoinTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeJoinTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeJoinTokenRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{21}
}

func (x *RevokeJoinTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// RevokeJoinTokenResponse acknowledges revocation.
type RevokeJoinTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeJoinTokenResponse) Reset() {
	*x = RevokeJoinTokenResponse{}
	mi := &file_cloud_v1_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeJoinTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeJoinTokenResponse) ProtoMessage() {}

func (x *RevokeJoinTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeJoinTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeJoinTokenResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_node_proto_rawDescGZIP(), []int{22}
}

var File_cloud_v1_node_proto protoreflect.FileDescriptor

const file_cloud_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x13cloud/v1/node.proto\x12\bcloud.v1\x1a\x15cloud/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\fNodeCapacity\x12\x12\n" +
	"\x04vcpu\x18\x01 \x01(\x05R\x04vcpu\x12\x15\n" +
	"\x06ram_mb\x18\x02 \x01(\x03R\x05ramMb\x12\x17\n" +
	"\adisk_gb\x18\x03 \x01(\x05R\x06diskGb\x12#\n" +
	"\rmax_workloads\x18\x04 \x01(\x05R\fmaxWorkloads\"\xb3\x01\n" +
	"\x0eNodeAllocation\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x03R\rcpuMillicores\x12\x15\n" +
	"\x06ram_mb\x18\x02 \x01(\x03R\x05ramMb\x12\x17\n" +
	"\adisk_gb\x18\x03 \x01(\x05R\x06diskGb\x12%\n" +
	"\x0eworkload_count\x18\x04 \x01(\x05R\rworkloadCount\x12#\n" +
	"\rrunning_count\x18\x05 \x01(\x05R\frunningCount\"\xd2\x01\n" +
	"\vNodeMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1e\n" +
	"\vmem_used_mb\x18\x02 \x01(\x03R\tmemUsedMb\x12 \n" +
	"\fdisk_used_gb\x18\x03 \x01(\x05R\n" +
	"diskUsedGb\x12%\n" +
	"\x0edocker_version\x18\x04 \x01(\tR\rdockerVersion\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x14\n" +
	"\x05load1\x18\a \x01(\x01R\x05load1\"\x95\a\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12,\n" +
	"\x06origin\x18\x04 \x01(\x0e2\x14.cloud.v1.NodeOriginR\x06origin\x120\n" +
	"\bprovider\x18\x05 \x01(\x0e2\x14.cloud.v1.ProviderIdR\bprovider\x12 \n" +
	"\fnode_type_id\x18\x06 \x01(\tR\n" +
	"nodeTypeId\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12,\n" +
	"\x06status\x18\b \x01(\x0e2\x14.cloud.v1.NodeStatusR\x06status\x12\x1a\n" +
	"\bhostname\x18\t \x01(\tR\bhostname\x12\x1b\n" +
	"\tpublic_ip\x18\n" +
	" \x01(\tR\bpublicIp\x12\x1d\n" +
	"\n" +
	"private_ip\x18\v \x01(\tR\tprivateIp\x122\n" +
	"\bcapacity\x18\f \x01(\v2\x16.cloud.v1.NodeCapacityR\bcapacity\x128\n" +
	"\n" +
	"allocation\x18\r \x01(\v2\x18.cloud.v1.NodeAllocationR\n" +
	"allocation\x12/\n" +
	"\ametrics\x18\x0e \x01(\v2\x15.cloud.v1.NodeMetricsR\ametrics\x122\n" +
	"\x06labels\x18\x0f \x03(\v2\x1a.cloud.v1.Node.LabelsEntryR\x06labels\x12+\n" +
	"\x11agent_fingerprint\x18\x10 \x01(\tR\x10agentFingerprint\x12!\n" +
	"\fprovision_id\x18\x11 \x01(\tR\vprovisionId\x12A\n" +
	"\x0elast_heartbeat\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tis_system\x18\x15 \x01(\bR\bisSystem\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x03\n" +
	"\tJoinToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\fnode_type_id\x18\x04 \x01(\tR\n" +
	"nodeTypeId\x12,\n" +
	"\x06origin\x18\x05 \x01(\x0e2\x14.cloud.v1.NodeOriginR\x06origin\x12!\n" +
	"\fprovision_id\x18\x06 \x01(\tR\vprovisionId\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x123\n" +
	"\aused_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06usedAt\x12%\n" +
	"\x0fused_by_node_id\x18\t \x01(\tR\fusedByNodeId\x129\n" +
	"\n" +
	"revoked_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x99\x01\n" +
	"\x10ListNodesRequest\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.cloud.v1.NodeStatusR\x06status\x12,\n" +
	"\x06origin\x18\x02 \x01(\x0e2\x14.cloud.v1.NodeOriginR\x06origin\x12)\n" +
	"\x04page\x18\x03 \x01(\v2\x15.cloud.v1.PageRequestR\x04page\"e\n" +
	"\x11ListNodesResponse\x12$\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0e.cloud.v1.NodeR\x05nodes\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cloud.v1.PageResponseR\x04page\" \n" +
	"\x0eGetNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetNodeResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.cloud.v1.NodeR\x04node\"\xf7\x01\n" +
	"\x11UpdateNodeRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12?\n" +
	"\x06labels\x18\x02 \x03(\v2'.cloud.v1.UpdateNodeRequest.LabelsEntryR\x06labels\x127\n" +
	"\bcapacity\x18\x03 \x01(\v2\x16.cloud.v1.NodeCapacityH\x01R\bcapacity\x88\x01\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_capacity\"8\n" +
	"\x12UpdateNodeResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.cloud.v1.NodeR\x04node\"\"\n" +
	"\x10DrainNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x11DrainNodeResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.cloud.v1.NodeR\x04node\"#\n" +
	"\x11ResumeNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x12ResumeNodeResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.cloud.v1.NodeR\x04node\"9\n" +
	"\x11DeleteNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x14\n" +
	"\x12DeleteNodeResponse\"o\n" +
	"\x16CreateJoinTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\fnode_type_id\x18\x02 \x01(\tR\n" +
	"nodeTypeId\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\x7f\n" +
	"\x17CreateJoinTokenResponse\x12)\n" +
	"\x05token\x18\x01 \x01(\v2\x13.cloud.v1.JoinTokenR\x05token\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12!\n" +
	"\fjoin_command\x18\x03 \x01(\tR\vjoinCommand\"B\n" +
	"\x15ListJoinTokensRequest\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.cloud.v1.PageRequestR\x04page\"q\n" +
	"\x16ListJoinTokensResponse\x12+\n" +
	"\x06tokens\x18\x01 \x03(\v2\x13.cloud.v1.JoinTokenR\x06tokens\x12*\n" +
	"\x04page\x18\x02 \x01(\v2\x16.cloud.v1.PageResponseR\x04page\"(\n" +
	"\x16RevokeJoinTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17RevokeJoinTokenResponse2\xb9\x05\n" +
	"\vNodeService\x12D\n" +
	"\tListNodes\x12\x1a.cloud.v1.ListNodesRequest\x1a\x1b.cloud.v1.ListNodesResponse\x12>\n" +
	"\aGetNode\x12\x18.cloud.v1.GetNodeRequest\x1a\x19.cloud.v1.GetNodeResponse\x12G\n" +
	"\n" +
	"UpdateNode\x12\x1b.cloud.v1.UpdateNodeRequest\x1a\x1c.cloud.v1.UpdateNodeResponse\x12D\n" +
	"\tDrainNode\x12\x1a.cloud.v1.DrainNodeRequest\x1a\x1b.cloud.v1.DrainNodeResponse\x12G\n" +
	"\n" +
	"ResumeNode\x12\x1b.cloud.v1.ResumeNodeRequest\x1a\x1c.cloud.v1.ResumeNodeResponse\x12G\n" +
	"\n" +
	"DeleteNode\x12\x1b.cloud.v1.DeleteNodeRequest\x1a\x1c.cloud.v1.DeleteNodeResponse\x12V\n" +
	"\x0fCreateJoinToken\x12 .cloud.v1.CreateJoinTokenRequest\x1a!.cloud.v1.CreateJoinTokenResponse\x12S\n" +
	"\x0eListJoinTokens\x12\x1f.cloud.v1.ListJoinTokensRequest\x1a .cloud.v1.ListJoinTokensResponse\x12V\n" +
	"\x0fRevokeJoinToken\x12 .cloud.v1.RevokeJoinTokenRequest\x1a!.cloud.v1.RevokeJoinTokenResponseB<Z:github.com/athNdev/carbon-panel/pkg/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_node_proto_rawDescOnce sync.Once
	file_cloud_v1_node_proto_rawDescData []byte
)

func file_cloud_v1_node_proto_rawDescGZIP() []byte {
	file_cloud_v1_node_proto_rawDescOnce.Do(func() {
		file_cloud_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_node_proto_rawDesc), len(file_cloud_v1_node_proto_rawDesc)))
	})
	return file_cloud_v1_node_proto_rawDescData
}

var file_cloud_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_cloud_v1_node_proto_goTypes = []any{
	(*NodeCapacity)(nil),            // 0: cloud.v1.NodeCapacity
	(*NodeAllocation)(nil),          // 1: cloud.v1.NodeAllocation
	(*NodeMetrics)(nil),             // 2: cloud.v1.NodeMetrics
	(*Node)(nil),                    // 3: cloud.v1.Node
	(*JoinToken)(nil),               // 4: cloud.v1.JoinToken
	(*ListNodesRequest)(nil),        // 5: cloud.v1.ListNodesRequest
	(*ListNodesResponse)(nil),       // 6: cloud.v1.ListNodesResponse
	(*GetNodeRequest)(nil),          // 7: cloud.v1.GetNodeRequest
	(*GetNodeResponse)(nil),         // 8: cloud.v1.GetNodeResponse
	(*UpdateNodeRequest)(nil),       // 9: cloud.v1.UpdateNodeRequest
	(*UpdateNodeResponse)(nil),      // 10: cloud.v1.UpdateNodeResponse
	(*DrainNodeRequest)(nil),        // 11: cloud.v1.DrainNodeRequest
	(*DrainNodeResponse)(nil),       // 12: cloud.v1.DrainNodeResponse
	(*ResumeNodeRequest)(nil),       // 13: cloud.v1.ResumeNodeRequest
	(*ResumeNodeResponse)(nil),      // 14: cloud.v1.ResumeNodeResponse
	(*DeleteNodeRequest)(nil),       // 15: cloud.v1.DeleteNodeRequest
	(*DeleteNodeResponse)(nil),      // 16: cloud.v1.DeleteNodeResponse
	(*CreateJoinTokenRequest)(nil),  // 17: cloud.v1.CreateJoinTokenRequest
	(*CreateJoinTokenResponse)(nil), // 18: cloud.v1.CreateJoinTokenResponse
	(*ListJoinTokensRequest)(nil),   // 19: cloud.v1.ListJoinTokensRequest
	(*ListJoinTokensResponse)(nil),  // 20: cloud.v1.ListJoinTokensResponse
	(*RevokeJoinTokenRequest)(nil),  // 21: cloud.v1.RevokeJoinTokenRequest
	(*RevokeJoinTokenResponse)(nil), // 22: cloud.v1.RevokeJoinTokenResponse
	nil,                             // 23: cloud.v1.Node.LabelsEntry
	nil,                             // 24: cloud.v1.UpdateNodeRequest.LabelsEntry
	(NodeOrigin)(0),                 // 25: cloud.v1.NodeOrigin
	(ProviderId)(0),                 // 26: cloud.v1.ProviderId
	(NodeStatus)(0),                 // 27: cloud.v1.NodeStatus
	(*timestamppb.Timestamp)(nil),   // 28: google.protobuf.Timestamp
	(*PageRequest)(nil),             // 29: cloud.v1.PageRequest
	(*PageResponse)(nil),            // 30: cloud.v1.PageResponse
}
var file_cloud_v1_node_proto_depIdxs = []int32{
	25, // 0: cloud.v1.Node.origin:type_name -> cloud.v1.NodeOrigin
	26, // 1: cloud.v1.Node.provider:type_name -> cloud.v1.ProviderId
	27, // 2: cloud.v1.Node.status:type_name -> cloud.v1.NodeStatus
	0,  // 3: cloud.v1.Node.capacity:type_name -> cloud.v1.NodeCapacity
	1,  // 4: cloud.v1.Node.allocation:type_name -> cloud.v1.NodeAllocation
	2,  // 5: cloud.v1.Node.metrics:type_name -> cloud.v1.NodeMetrics
	23, // 6: cloud.v1.Node.labels:type_name -> cloud.v1.Node.LabelsEntry
	28, // 7: cloud.v1.Node.last_heartbeat:type_name -> google.protobuf.Timestamp
	28, // 8: cloud.v1.Node.created_at:type_name -> google.protobuf.Timestamp
	28, // 9: cloud.v1.Node.updated_at:type_name -> google.protobuf.Timestamp
	25, // 10: cloud.v1.JoinToken.origin:type_name -> cloud.v1.NodeOrigin
	28, // 11: cloud.v1.JoinToken.expires_at:type_name -> google.protobuf.Timestamp
	28, // 12: cloud.v1.JoinToken.used_at:type_name -> google.protobuf.Timestamp
	28, // 13: cloud.v1.JoinToken.revoked_at:type_name -> google.protobuf.Timestamp
	28, // 14: cloud.v1.JoinToken.created_at:type_name -> google.protobuf.Timestamp
	27, // 15: cloud.v1.ListNodesRequest.status:type_name -> cloud.v1.NodeStatus
	25, // 16: cloud.v1.ListNodesRequest.origin:type_name -> cloud.v1.NodeOrigin
	29, // 17: cloud.v1.ListNodesRequest.page:type_name -> cloud.v1.PageRequest
	3,  // 18: cloud.v1.ListNodesResponse.nodes:type_name -> cloud.v1.Node
	30, // 19: cloud.v1.ListNodesResponse.page:type_name -> cloud.v1.PageResponse
	3,  // 20: cloud.v1.GetNodeResponse.node:type_name -> cloud.v1.Node
	24, // 21: cloud.v1.UpdateNodeRequest.labels:type_name -> cloud.v1.UpdateNodeRequest.LabelsEntry
	0,  // 22: cloud.v1.UpdateNodeRequest.capacity:type_name -> cloud.v1.NodeCapacity
	3,  // 23: cloud.v1.UpdateNodeResponse.node:type_name -> cloud.v1.Node
	3,  // 24: cloud.v1.DrainNodeResponse.node:type_name -> cloud.v1.Node
	3,  // 25: cloud.v1.ResumeNodeResponse.node:type_name -> cloud.v1.Node
	4,  // 26: cloud.v1.CreateJoinTokenResponse.token:type_name -> cloud.v1.JoinToken
	29, // 27: cloud.v1.ListJoinTokensRequest.page:type_name -> cloud.v1.PageRequest
	4,  // 28: cloud.v1.ListJoinTokensResponse.tokens:type_name -> cloud.v1.JoinToken
	30, // 29: cloud.v1.ListJoinTokensResponse.page:type_name -> cloud.v1.PageResponse
	5,  // 30: cloud.v1.NodeService.ListNodes:input_type -> cloud.v1.ListNodesRequest
	7,  // 31: cloud.v1.NodeService.GetNode:input_type -> cloud.v1.GetNodeRequest
	9,  // 32: cloud.v1.NodeService.UpdateNode:input_type -> cloud.v1.UpdateNodeRequest
	11, // 33: cloud.v1.NodeService.DrainNode:input_type -> cloud.v1.DrainNodeRequest
	13, // 34: cloud.v1.NodeService.ResumeNode:input_type -> cloud.v1.ResumeNodeRequest
	15, // 35: cloud.v1.NodeService.DeleteNode:input_type -> cloud.v1.DeleteNodeRequest
	17, // 36: cloud.v1.NodeService.CreateJoinToken:input_type -> cloud.v1.CreateJoinTokenRequest
	19, // 37: cloud.v1.NodeService.ListJoinTokens:input_type -> cloud.v1.ListJoinTokensRequest
	21, // 38: cloud.v1.NodeService.RevokeJoinToken:input_type -> cloud.v1.RevokeJoinTokenRequest
	6,  // 39: cloud.v1.NodeService.ListNodes:output_type -> cloud.v1.ListNodesResponse
	8,  // 40: cloud.v1.NodeService.GetNode:output_type -> cloud.v1.GetNodeResponse
	10, // 41: cloud.v1.NodeService.UpdateNode:output_type -> cloud.v1.UpdateNodeResponse
	12, // 42: cloud.v1.NodeService.DrainNode:output_type -> cloud.v1.DrainNodeResponse
	14, // 43: cloud.v1.NodeService.ResumeNode:output_type -> cloud.v1.ResumeNodeResponse
	16, // 44: cloud.v1.NodeService.DeleteNode:output_type -> cloud.v1.DeleteNodeResponse
	18, // 45: cloud.v1.NodeService.CreateJoinToken:output_type -> cloud.v1.CreateJoinTokenResponse
	20, // 46: cloud.v1.NodeService.ListJoinTokens:output_type -> cloud.v1.ListJoinTokensResponse
	22, // 47: cloud.v1.NodeService.RevokeJoinToken:output_type -> cloud.v1.RevokeJoinTokenResponse
	39, // [39:48] is the sub-list for method output_type
	30, // [30:39] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_cloud_v1_node_proto_init() }
func file_cloud_v1_node_proto_init() {
	if File_cloud_v1_node_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	file_cloud_v1_node_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_node_proto_rawDesc), len(file_cloud_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_v1_node_proto_goTypes,
		DependencyIndexes: file_cloud_v1_node_proto_depIdxs,
		MessageInfos:      file_cloud_v1_node_proto_msgTypes,
	}.Build()
	File_cloud_v1_node_proto = out.File
	file_cloud_v1_node_proto_goTypes = nil
	file_cloud_v1_node_proto_depIdxs = nil
}
