// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: carbonpanel/v1/backup.proto

package carbonpanelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One backup record
type BackupRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Locked        bool                   `protobuf:"varint,6,opt,name=locked,proto3" json:"locked,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRecord) Reset() {
	*x = BackupRecord{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRecord) ProtoMessage() {}

func (x *BackupRecord) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRecord.ProtoReflect.Descriptor instead.
func (*BackupRecord) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{0}
}

func (x *BackupRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackupRecord) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *BackupRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupRecord) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BackupRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BackupRecord) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *BackupRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BackupRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// List request
type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{1}
}

func (x *ListBackupsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListBackupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// List response
type ListBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*BackupRecord        `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{2}
}

func (x *ListBackupsResponse) GetBackups() []*BackupRecord {
	if x != nil {
		return x.Backups
	}
	return nil
}

// Delete request
type DeleteBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupRequest) Reset() {
	*x = DeleteBackupRequest{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupRequest) ProtoMessage() {}

func (x *DeleteBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackupRequest) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Delete response
type DeleteBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackupResponse) Reset() {
	*x = DeleteBackupResponse{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackupResponse) ProtoMessage() {}

func (x *DeleteBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackupResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackupResponse) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Restore request
type RestoreBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreBackupRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Restore response
type RestoreBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupResponse) Reset() {
	*x = RestoreBackupResponse{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupResponse) ProtoMessage() {}

func (x *RestoreBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Lock request
type SetBackupLockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Locked        bool                   `protobuf:"varint,2,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBackupLockedRequest) Reset() {
	*x = SetBackupLockedRequest{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBackupLockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBackupLockedRequest) ProtoMessage() {}

func (x *SetBackupLockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBackupLockedRequest.ProtoReflect.Descriptor instead.
func (*SetBackupLockedRequest) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{7}
}

func (x *SetBackupLockedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetBackupLockedRequest) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

// Lock response
type SetBackupLockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backup        *BackupRecord          `protobuf:"bytes,1,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBackupLockedResponse) Reset() {
	*x = SetBackupLockedResponse{}
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBackupLockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBackupLockedResponse) ProtoMessage() {}

func (x *SetBackupLockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carbonpanel_v1_backup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBackupLockedResponse.ProtoReflect.Descriptor instead.
func (*SetBackupLockedResponse) Descriptor() ([]byte, []int) {
	return file_carbonpanel_v1_backup_proto_rawDescGZIP(), []int{8}
}

func (x *SetBackupLockedResponse) GetBackup() *BackupRecord {
	if x != nil {
		return x.Backup
	}
	return nil
}

var File_carbonpanel_v1_backup_proto protoreflect.FileDescriptor

const file_carbonpanel_v1_backup_proto_rawDesc = "" +
	"\n" +
	"\x1bcarbonpanel/v1/backup.proto\x12\x0ecarbonpanel.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\fBackupRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06locked\x18\x06 \x01(\bR\x06locked\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"G\n" +
	"\x12ListBackupsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"M\n" +
	"\x13ListBackupsResponse\x126\n" +
	"\abackups\x18\x01 \x03(\v2\x1c.carbonpanel.v1.BackupRecordR\abackups\"%\n" +
	"\x13DeleteBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"&\n" +
	"\x14RestoreBackupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15RestoreBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x16SetBackupLockedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06locked\x18\x02 \x01(\bR\x06locked\"O\n" +
	"\x17SetBackupLockedResponse\x124\n" +
	"\x06backup\x18\x01 \x01(\v2\x1c.carbonpanel.v1.BackupRecordR\x06backup2\x84\x03\n" +
	"\rBackupService\x12V\n" +
	"\vListBackups\x12\".carbonpanel.v1.ListBackupsRequest\x1a#.carbonpanel.v1.ListBackupsResponse\x12Y\n" +
	"\fDeleteBackup\x12#.carbonpanel.v1.DeleteBackupRequest\x1a$.carbonpanel.v1.DeleteBackupResponse\x12\\\n" +
	"\rRestoreBackup\x12$.carbonpanel.v1.RestoreBackupRequest\x1a%.carbonpanel.v1.RestoreBackupResponse\x12b\n" +
	"\x0fSetBackupLocked\x12&.carbonpanel.v1.SetBackupLockedRequest\x1a'.carbonpanel.v1.SetBackupLockedResponseBHZFgithub.com/athNdev/carbon-panel/pkg/proto/carbonpanel/v1;carbonpanelv1b\x06proto3"

var (
	file_carbonpanel_v1_backup_proto_rawDescOnce sync.Once
	file_carbonpanel_v1_backup_proto_rawDescData []byte
)

func file_carbonpanel_v1_backup_proto_rawDescGZIP() []byte {
	file_carbonpanel_v1_backup_proto_rawDescOnce.Do(func() {
		file_carbonpanel_v1_backup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carbonpanel_v1_backup_proto_rawDesc), len(file_carbonpanel_v1_backup_proto_rawDesc)))
	})
	return file_carbonpanel_v1_backup_proto_rawDescData
}

var file_carbonpanel_v1_backup_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_carbonpanel_v1_backup_proto_goTypes = []any{
	(*BackupRecord)(nil),            // 0: carbonpanel.v1.BackupRecord
	(*ListBackupsRequest)(nil),      // 1: carbonpanel.v1.ListBackupsRequest
	(*ListBackupsResponse)(nil),     // 2: carbonpanel.v1.ListBackupsResponse
	(*DeleteBackupRequest)(nil),     // 3: carbonpanel.v1.DeleteBackupRequest
	(*DeleteBackupResponse)(nil),    // 4: carbonpanel.v1.DeleteBackupResponse
	(*RestoreBackupRequest)(nil),    // 5: carbonpanel.v1.RestoreBackupRequest
	(*RestoreBackupResponse)(nil),   // 6: carbonpanel.v1.RestoreBackupResponse
	(*SetBackupLockedRequest)(nil),  // 7: carbonpanel.v1.SetBackupLockedRequest
	(*SetBackupLockedResponse)(nil), // 8: carbonpanel.v1.SetBackupLockedResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_carbonpanel_v1_backup_proto_depIdxs = []int32{
	9, // 0: carbonpanel.v1.BackupRecord.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: carbonpanel.v1.ListBackupsResponse.backups:type_name -> carbonpanel.v1.BackupRecord
	0, // 2: carbonpanel.v1.SetBackupLockedResponse.backup:type_name -> carbonpanel.v1.BackupRecord
	1, // 3: carbonpanel.v1.BackupService.ListBackups:input_type -> carbonpanel.v1.ListBackupsRequest
	3, // 4: carbonpanel.v1.BackupService.DeleteBackup:input_type -> carbonpanel.v1.DeleteBackupRequest
	5, // 5: carbonpanel.v1.BackupService.RestoreBackup:input_type -> carbonpanel.v1.RestoreBackupRequest
	7, // 6: carbonpanel.v1.BackupService.SetBackupLocked:input_type -> carbonpanel.v1.SetBackupLockedRequest
	2, // 7: carbonpanel.v1.BackupService.ListBackups:output_type -> carbonpanel.v1.ListBackupsResponse
	4, // 8: carbonpanel.v1.BackupService.DeleteBackup:output_type -> carbonpanel.v1.DeleteBackupResponse
	6, // 9: carbonpanel.v1.BackupService.RestoreBackup:output_type -> carbonpanel.v1.RestoreBackupResponse
	8, // 10: carbonpanel.v1.BackupService.SetBackupLocked:output_type -> carbonpanel.v1.SetBackupLockedResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_carbonpanel_v1_backup_proto_init() }
func file_carbonpanel_v1_backup_proto_init() {
	if File_carbonpanel_v1_backup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carbonpanel_v1_backup_proto_rawDesc), len(file_carbonpanel_v1_backup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carbonpanel_v1_backup_proto_goTypes,
		DependencyIndexes: file_carbonpanel_v1_backup_proto_depIdxs,
		MessageInfos:      file_carbonpanel_v1_backup_proto_msgTypes,
	}.Build()
	File_carbonpanel_v1_backup_proto = out.File
	file_carbonpanel_v1_backup_proto_goTypes = nil
	file_carbonpanel_v1_backup_proto_depIdxs = nil
}
